const lang = {
  vms_download: "Спампаваць",
  vms_loading: 'Загрузка...',
  vms_error: "Памылка",
  vms_download_cover: "Спампаваць вокладку",
  vms_download_playlist: "Спампаваць плэйліст",
  vms_download_tracklist: 'Скачать список треков (.txt)',
  vms_downloading: "Спампоўваецца...",
  vms_playlist_is_empty: "Плэйліст пусты.",
  vms_playlist_not_found: "Плэйліст не знойдзены",
  vms_audio_not_found: "Не атрымалася атрымаць дадзеныя пра трэк",
  vms_audio_url_not_found: "Адсутнічае спасылка на трэк",
  vms_album_cover_not_found: "У гэтага альбома няма вокладкі",
  vms_fs_music_done: "Спампоўванне музыкі завершана",
  vms_fs_music_playlist_done: "Спампоўванне плэйліста завершана",
  vms_fs_method_selection: "Абярыце спосаб спампоўвання файлаў",
  vms_fs_error_selecting_directory: "Памылка: не ўдалося абраць папку для захавання",
  vms_fs_option_zip_title: "zip-архіў",
  vms_fs_option_zip_description: "Упампоўванне адным файлам. Архівацыя адбываецца падчас упампоўвання без нагрузкі на сістэму.",
  vms_fs_option_folder_title: "Напрамую ў папку",
  vms_fs_option_folder_description: "Вам прапанавана выбраць месца для стварэння новай папкі, у якую файлы будуць упампоўвацца наўпрост на дыск.",
  vms_fs_option_unselected_title: "Заўсёды пытаць",
  vms_fs_download_method_title: "Спосаб спампоўвання файлаў",
  vms_fs_select_zip: "Спампаваць",
  vms_fs_select_folder: "Абраць папку",
  vms_download_all_my_music: "Спампаваць усе мае трэкі",
  vms_download_all_music: "Спампаваць усе трэкі гэтага карыстальніка",
  vms_sett_num_tracks_in_playlist: "Нумараваць трэкі ў плэйлісце",
  vms_sett_save_method_selection: "Запомніць абраны спосаб спампоўвання",
  vms_sett_save_method_selection_description: "Вы заўсёды можаце змяніць спосаб у наладах пашырэння",
  vms_playlist_download_auth_required: "Для упампоўвання плэйлістоў неабходна ўвайсці ў акаўнт",
  vms_download_manager_active_tasks: "Актыўныя загрузкі",
  vms_download_manager_finished_tasks: "Завершаныя загрузкі",
  vms_download_manager_save: "Захаваць",
  vms_download_manager_remove: "Выдаліць",
  vms_download_manager_cancel: "Скасаваць",
  vms_playlist_track_download_completed: "{trackName} — завершана",
  vms_playlist_download_completed: `Спампавана {total}`,
  vms_tracks_plurals: ["трэк", "трэка", "трэкаў"],
  vms_seconds_plurals: ['секунда', 'секунды', 'секунд'],
  vms_sett_audio_convert_mode_title: "Метад канвертацыі трэкаў",
  vms_sett_audio_convert_mode_ffmpeg_desc: "На старых сістэмах можа не працаваць.",
  vms_sett_audio_convert_mode_desc: "УКантакце аддае трэкі ў фармаце m3u8, а пашырэнне канвертуе ў звыклы mp3",
  vms_sett_audio_convert_mode_vknext: 'Сервер VK Next',
  vms_sett_audio_convert_mode_vknext_desc: "Выкарыстоўвае FFmpeg на серверы. Ідэальна для вялікіх плэйлістоў, бо не нагружае ваш працэсар. Пры высокай нагрузцы на сервер хуткасць можа зніжацца.",
  vms_settings_title: "Налады VK Music Saver",
  vms_settings_review_in_firefox: "Ацаніць у Firefox Add-ons",
  vms_settings_review_in_chrome: "Ацаніць у Chrome Web Store",
  vms_settings_donate: "Падтрымаць распрацоўшчыкаў",
  vms_share: "Падзяліцца",
  vms_clear_storage: "Скінуць налады",
  vms_clear_track_details_storage: 'Очистить кэш треков',
  vms_clear_track_details_storage_description: 'Размер и битрейт',
  vms_created_by: "Створана камандай {name}",
  vms_link_copied: "Спасылка скапіяваная",
  vms_badges_deluxe_function_warning: "Функцыя даступная для ўладальнікаў падпіскі Прайм Дэ Люкс.",
  vms_onboarding_settings_hint_title: "Налады VK Music Saver",
  vms_onboarding_settings_hint_description: "У іх можна наладзіць спампоўванне так, як зручна менавіта вам",
  vms_sett_single_track_template: "Фармат назвы асобнага трэка",
  vms_sett_playlist_track_template: "Фармат назвы трэка ў плэйлісце",
  vms_sett_audio_write_id3_tags: "Дадаваць ID3 тэгі да музыкі",
  vms_sett_audio_write_id3_tags_desc: "Трэкі і альбомы будуць спампоўвацца з метаданымі, такімі як імя выканаўцы, назва, дата выпуску і вокладка",
  vms_sett_audio_write_genius_lyrics: "Устаўляць у метаданыя трэкаў тэксты з Genius",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver не звязаны з гэтым сайтам і не нясе адказнасці за дакладнасць тэкстаў песень",
  vms_sett_show_bitrate_near_duration: "Паказваць бітрэйт трэка каля працягласці",
  vms_alert_rating_title: "Вам падабаецца VK Music Saver?",
  vms_alert_rating_desc: "Калі ласка, падтрымайце пашырэнне ў рэйтынгу {storeName}",
  vms_alert_rating_yes: "Ацаніць пашырэнне",
  vms_alert_donate_title: "Падтрымайце распрацоўшчыкаў",
  vms_alert_donate_desc: "VK Music Saver ствараецца на энтузіязме — бясплатна, без рэкламы, без схаваных збораў даных і з адкрытым зыходным кодам. Калі пашырэнне вам падабаецца, падтрымайце нас данатам",
  vms_alert_donate_yes: "Падтрымаць",
  vms_alert_base_no: "Не, дзякуй",
  vms_sett_download_playlist_in_reverse: "Спампоўваць плэйлісты ў адваротным парадку — з апошняга трэка да першага",
  vms_vmk_warning_title: "Пашырэнне не працуе ў мабільнай версіі сайта",
  vms_vmk_warning_go_vkcom: "Перайсці на камп'ютарную версію сайта",
  vms_vmk_warning_hide: "Не паказваць зноў",
  vms_sett_add_leading_zeros: "Фарматаваць нумары трэкаў з вядучымі нулямі",
  vms_sett_add_leading_zeros_desc: "Напрыклад: 01, 02, 03 … замест 1, 2, 3",
  vms_concurrent_downloads_recommendation: "Спампоўвайце не больш за два плэйлісты адразу, інакш браўзер можа завіснуць",
  vms_settings_need_reload_page: "Перазагрузіце старонку, каб змены ўступілі ў сілу",
  vms_preparing_tracklist: 'Получаем список треков...',
  vms_download_manager_progress_full: '{loaded} из {total}, {speed}/с ({eta})',
  vms_download_manager_progress_basic: '{loaded} из {total}, {speed}/с',
  vms_size_units: ['Б', 'КБ', 'МБ', 'ГБ', 'ТБ', 'ПБ', 'ЭБ', 'ЗБ', 'ЙБ'],
  vms_eta_almost_done: 'около секунды'
};
export default lang;