const lang = {
  vms_download: "Спампаваць",
  vms_loading: 'Загрузка...',
  vms_error: "Памылка",
  vms_download_cover: "Спампаваць вокладку",
  vms_download_playlist: "Спампаваць плэйліст",
  vms_downloading: "Спампоўваецца...",
  vms_playlist_is_empty: "Плэйліст пусты.",
  vms_playlist_not_found: "Плэйліст не знойдзены",
  vms_audio_not_found: "УКантакце не вярнуў інфармацыю пра трэк",
  vms_audio_url_not_found: "Адсутнічае спасылка на трэк",
  vms_album_cover_not_found: "У гэтага альбома няма вокладкі",
  vms_archivation: "архівацыя...",
  vms_fs_music_done: "Спампоўванне музыкі завершана",
  vms_fs_music_playlist_done: "Спампоўванне плэйліста завершана",
  vms_fs_method_selection: "Абярыце спосаб спампоўвання файлаў",
  vms_fs_error_selecting_directory: "Памылка: не ўдалося абраць папку для захавання",
  vms_fs_option_zip_title: "zip-архіў",
  vms_fs_option_zip_description: "Усе файлы будуць загружаныя ў аператыўную памяць, а затым упакаваныя ў архіў, месца захавання якога будзе прапанавана вам.",
  vms_fs_option_folder_title: "Напрамую ў папку",
  vms_fs_option_folder_description: "Вам будзе прапанавана абраць месца для стварэння новай папкі, у якую загрузяцца файлы без папярэдняга захавання ў аператыўнай памяці.",
  vms_fs_option_unselected_title: "Заўсёды пытаць",
  vms_fs_download_method_title: "Спосаб спампоўвання файлаў",
  vms_fs_select_zip: "Спампаваць",
  vms_fs_select_folder: "Абраць папку",
  vms_fs_select_recommended: "Рэкамендаваны спосаб",
  vms_download_all_my_music: "Спампаваць усе мае трэкі",
  vms_download_all_music: "Спампаваць усе трэкі гэтага карыстальніка",
  vms_sett_num_tracks_in_playlist: "Нумараваць трэкі ў плэйлісце",
  vms_sett_save_method_selection: "Запомніць абраны спосаб спампоўвання",
  vms_sett_save_method_selection_description: "Вы заўсёды можаце змяніць спосаб у наладах пашырэння",
  vms_playlist_download_auth_required: "Вы павінны быць аўтарызаваныя для спампоўвання плэйлістоў",
  vms_download_manager_active_tasks: "Актыўныя загрузкі",
  vms_download_manager_finished_tasks: "Завершаныя загрузкі",
  vms_download_manager_save: "Захаваць",
  vms_download_manager_remove: "Выдаліць",
  vms_download_manager_cancel: "Скасаваць",
  vms_playlist_track_download_completed: "{trackName} - завершана",
  vms_playlist_download_completed: `Спампавана {total}`,
  vms_tracks_plurals: ["трэк", "трэка", "трэкаў"],
  vms_sett_audio_convert_mode_title: "Метад канвертацыі трэкаў",
  vms_sett_audio_convert_mode_ffmpeg_desc: "На старых сістэмах можа не працаваць.",
  vms_sett_audio_convert_mode_hlsjs_desc: "У Firefox могуць быць праблемы.",
  vms_sett_audio_convert_mode_desc: "УКантакце аддае трэкі ў фармаце m3u8, а пашырэнне канвертуе ў звыклы mp3",
  vms_sett_audio_convert_mode_vknext: 'Сервер VK Next',
  vms_sett_audio_convert_mode_vknext_desc: "Выкарыстоўвае FFmpeg для канвертацыі. Лепш за іншых падыходзіць для загрузкі вялікіх плэйлістоў, бо канвертацыя не займае аператыўную памяць. Аднак можа працаваць павольна, калі гэты спосаб адначасова выкарыстоўвае вялікая колькасць карыстальнікаў.",
  vms_settings_title: "Налады VK Music Saver",
  vms_settings_review_in_firefox: "Ацаніць у Firefox Add-ons",
  vms_settings_review_in_chrome: "Ацаніць у Chrome Web Store",
  vms_settings_donate: "Падтрымаць распрацоўшчыкаў",
  vms_share: "Падзяліцца",
  vms_clear_storage: "Скінуць налады",
  vms_created_by: "Створана камандай {name}",
  vms_link_copied: "Спасылка скапіяваная",
  vms_badges_deluxe_function_warning: "Функцыя даступная для ўладальнікаў падпіскі Прайм Дэ Люкс.",
  vms_onboarding_settings_hint_title: "Налады VK Music Saver",
  vms_onboarding_settings_hint_description: "У іх можна наладзіць спампоўванне так, як зручна менавіта вам",
  vms_sett_single_track_template: "Фармат назвы асобнага трэка",
  vms_sett_playlist_track_template: "Фармат назвы трэка ў плэйлісце",
  vms_sett_audio_write_id3_tags: "Дадаваць ID3 тэгі да музыкі",
  vms_sett_audio_write_id3_tags_desc: "Трэкі і альбомы будуць спампоўвацца з метаданымі, такімі як імя выканаўцы, назва, дата выпуску і вокладка",
  vms_sett_audio_write_genius_lyrics: "Устаўляць у метаданыя трэкаў тэксты з Genius",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver не звязаны з гэтым сайтам і не нясе адказнасці за дакладнасць тэкстаў песень",
  vms_sett_show_bitrate_near_duration: "Паказваць бітрэйт трэка каля працягласці",
  vms_alert_rating_title: "Вам падабаецца VK Music Saver?",
  vms_alert_rating_desc: "Калі ласка, падтрымайце пашырэнне ў рэйтынгу {storeName}",
  vms_alert_rating_yes: "Ацаніць пашырэнне",
  vms_alert_donate_title: "Падтрымайце распрацоўшчыкаў",
  vms_alert_donate_desc: "VK Music Saver ствараецца на энтузіязме — бясплатна, без рэкламы, без схаваных збораў даных і з адкрытым зыходным кодам. Калі пашырэнне вам падабаецца, падтрымайце нас данатам",
  vms_alert_donate_yes: "Падтрымаць",
  vms_alert_base_no: "Не, дзякуй",
  vms_sett_download_playlist_in_reverse: "Спампоўваць плэйлісты ў адваротным парадку — з апошняга трэка да першага",
  vms_vmk_warning_title: "Пашырэнне не працуе ў мабільнай версіі сайта",
  vms_vmk_warning_go_vkcom: "Перайсці на камп'ютарную версію сайта",
  vms_vmk_warning_hide: "Не паказваць зноў",
  vms_sett_add_leading_zeros: "Фарматаваць нумары трэкаў з вядучымі нулямі",
  vms_sett_add_leading_zeros_desc: "Напрыклад: 01, 02, 03 … замест 1, 2, 3",
  installed_header_title: "Пашырэнне ўсталявана",
  installed_how_title: "Як працуе пашырэнне:",
  installed_step_1: "Перайдзіце ў раздзел з музыкай",
  installed_step_2: "Побач з кожным трэкам адлюструецца кнопка спампоўвання і інфармацыя пра бітрэйт.",
  installed_step_3: "Націсніце на кнопку, каб спампаваць трэк.",
  installed_reload_notice: "Калі ў вас ужо адкрыты сайт {site}, трэба перазагрузіць укладку, каб пашырэнне запрацавала.",
  installed_attention: "Звярніце ўвагу",
  installed_pc_version_only: "Пашырэнне працуе толькі ў поўнай версіі сайта {site}. Пры выкарыстанні мабільнай версіі m.vk.ru пашырэнне не будзе працаваць.",
  installed_follow_community: "Падпішыцеся на {link}. Там аператыўна выкладваецца важная інфармацыя для карыстальнікаў пашырэння!",
  installed_follow_community_link: "наша суполка УКантакце",
  installed_ffmpeg_notice_1: "Калі ў вас Firefox і не спампоўваюцца трэкі, хутчэй за ўсё праблема ў ffmpeg (канвертацыя трэкаў).",
  installed_ffmpeg_notice_2: "УКантакце аддае трэкі ў фармаце m3u8, а пашырэнне канвертуе ў звыклы mp3.",
  installed_ffmpeg_notice_3: "У Firefox па змаўчанні пашырэнне выкарыстоўвае FFmpeg, размешчаны на нашым сайце {site}. Калі сайт недаступны — канвертацыя не працуе, і пашырэнне не зможа спампаваць трэк.",
  installed_ffmpeg_notice_4: "У наладах пашырэння можна пераключыцца на метад hls.js. Ён не залежыць ад нашага сайта, але ў Firefox працуе нестабільна — магчымыя пстрычкі або скажэнні ў гуку.",
  vms_concurrent_downloads_recommendation: "Спампоўвайце не больш за два плэйлісты адразу, інакш браўзер можа завіснуць",
  vms_settings_need_reload_page: "Перазагрузіце старонку, каб змены ўступілі ў сілу"
};
export default lang;