const lang = {
	vms_download: 'Скачать',
	vms_loading: 'Загрузка...',
	vms_error: 'Ошибка',
	vms_download_cover: 'Скачать обложку',
	vms_download_playlist: 'Скачать плейлист',
	vms_downloading: 'Скачивается...',
	vms_playlist_is_empty: 'Плейлист пуст.',
	vms_playlist_not_found: 'Плейлист не найден',
	vms_audio_not_found: 'ВКонтакте не вернул информацию о треке',
	vms_audio_url_not_found: 'Отсутствует ссылка на трек',
	vms_album_cover_not_found: 'У этого альбома нет обложки',
	vms_archivation: 'архивация...',
	vms_fs_music_done: 'Скачивание музыки завершено',
	vms_fs_music_playlist_done: 'Скачивание плейлиста завершено',
	vms_fs_method_selection: 'Выберите способ скачивания файлов',
	vms_fs_error_selecting_directory: 'Ошибка: не удалось выбрать папку для сохранения',
	vms_fs_option_zip_title: 'zip-архив',
	vms_fs_option_zip_description:
		'Все файлы будут загружены в оперативную память, а затем упакованы в архив, место сохранения которого будет предложено вам.',
	vms_fs_option_folder_title: 'Напрямую в папку',
	vms_fs_option_folder_description:
		'Вам будет предложен выбор места для создания новой папки, в которую загрузятся файлы без предварительного сохранения в оперативной памяти.',
	vms_fs_option_unselected_title: 'Всегда спрашивать',
	vms_fs_download_method_title: 'Способ скачивания файлов',
	vms_fs_select_zip: 'Скачать',
	vms_fs_select_folder: 'Выбрать папку',
	vms_fs_select_recommended: 'Рекомендуемый способ',
	vms_download_all_music: 'Скачать всю музыку',
	vms_sett_num_tracks_in_playlist: 'Нумеровать треки',
	vms_sett_save_method_selection: 'Запомнить выбранный способ скачивания',
	vms_sett_save_method_selection_description: 'Вы всегда можете изменить способ в настройках расширения',
	vms_playlist_download_auth_required: 'Вы должны быть авторизованы для скачивания плейлистов',
	vms_download_manager_active_tasks: 'Активные загрузки',
	vms_download_manager_finished_tasks: 'Завершенные загрузки',
	vms_download_manager_save: 'Сохранить',
	vms_download_manager_remove: 'Удалить',
	vms_download_manager_cancel: 'Отменить',
	vms_playlist_track_download_completed: '{trackName} - завершено',
	vms_playlist_download_completed: `Скачано {total}`,
	vkcom_tracks_plurals: ['трек', 'трека', 'треков'],
	vms_sett_audio_convert_mode_title: 'Метод конвертации треков из m3u8 в mp3',
	vms_sett_audio_convert_mode_ffmpeg_desc: 'На старых системах может не работать',
	vms_sett_audio_convert_mode_hlsjs_desc: 'В Firefox могут быть проблемы',
	vms_sett_audio_convert_mode_desc: 'Используется при скачивании треков и плейлистов',
	vms_settings_title: 'Настройки VK Music Saver',
	vms_settings_review_in_firefox: 'Оценить в Firefox Add-ons',
	vms_settings_review_in_chrome: 'Оценить в Chrome Web Store',
	vms_share: 'Поделиться',
	vms_creator: 'Создатель',
	vms_link_copied: 'Ссылка скопирована',
};

export default lang;
