const lang = {
	vms_download: 'Скачать',
	vms_loading: 'Загрузка...',
	vms_error: 'Ошибка',
	vms_download_cover: 'Скачать обложку',
	vms_download_playlist: 'Скачать плейлист',
	vms_downloading: 'Скачивается...',
	vms_playlist_is_empty: 'Плейлист пуст.',
	vms_playlist_not_found: 'Плейлист не найден',
	vms_audio_not_found: 'Не удалось получить данные о треке',
	vms_audio_url_not_found: 'Отсутствует ссылка на трек',
	vms_album_cover_not_found: 'У этого альбома нет обложки',
	vms_fs_music_done: 'Скачивание музыки завершено',
	vms_fs_music_playlist_done: 'Скачивание плейлиста завершено',
	vms_fs_method_selection: 'Выберите способ скачивания файлов',
	vms_fs_error_selecting_directory: 'Ошибка: не удалось выбрать папку для сохранения',
	vms_fs_option_zip_title: 'zip-архив',
	vms_fs_option_zip_description:
		'Скачивание одним файлом. Архивация происходит в процессе скачивания без нагрузки на систему.',
	vms_fs_option_folder_title: 'Напрямую в папку',
	vms_fs_option_folder_description:
		'Вам предложен выбор места для создания новой папки, в которую загрузятся файлы напрямую на диск.',
	vms_fs_option_unselected_title: 'Всегда спрашивать',
	vms_fs_download_method_title: 'Способ скачивания файлов',
	vms_fs_select_zip: 'Скачать',
	vms_fs_select_folder: 'Выбрать папку',
	vms_download_all_my_music: 'Скачать все мои треки',
	vms_download_all_music: 'Скачать все треки этого пользователя',
	vms_sett_num_tracks_in_playlist: 'Нумеровать треки в плейлисте',
	vms_sett_save_method_selection: 'Запомнить выбранный способ скачивания',
	vms_sett_save_method_selection_description: 'Вы всегда можете изменить способ в настройках расширения',
	vms_playlist_download_auth_required: 'Для скачивания плейлистов необходимо войти в аккаунт',
	vms_download_manager_active_tasks: 'Активные загрузки',
	vms_download_manager_finished_tasks: 'Завершенные загрузки',
	vms_download_manager_save: 'Сохранить',
	vms_download_manager_remove: 'Удалить',
	vms_download_manager_cancel: 'Отменить',
	vms_playlist_track_download_completed: '{trackName} — завершено',
	vms_playlist_download_completed: `Скачано {total}`,
	vms_tracks_plurals: ['трек', 'трека', 'треков'],
	vms_sett_audio_convert_mode_title: 'Метод конвертации треков',
	vms_sett_audio_convert_mode_ffmpeg_desc: 'На старых системах может не работать.',
	vms_sett_audio_convert_mode_hlsjs_desc: 'В Firefox могут быть проблемы.',
	vms_sett_audio_convert_mode_desc:
		'ВКонтакте отдает треки в формате m3u8, а расширение конвертирует в привычный mp3',
	vms_sett_audio_convert_mode_vknext: 'Сервер VK Next',
	vms_sett_audio_convert_mode_vknext_desc:
		'Использует FFmpeg на сервере. Идеально для больших плейлистов так как не нагружает ваш процессор. При высокой нагрузке на сервер скорость может снижаться.',
	vms_settings_title: 'Настройки VK Music Saver',
	vms_settings_review_in_firefox: 'Оценить в Firefox Add-ons',
	vms_settings_review_in_chrome: 'Оценить в Chrome Web Store',
	vms_settings_donate: 'Поддержать разработчиков',
	vms_share: 'Поделиться',
	vms_clear_storage: 'Сбросить настройки',
	vms_created_by: 'Создано командой {name}',
	vms_link_copied: 'Ссылка скопирована',
	vms_badges_deluxe_function_warning: 'Функция доступна для обладателей подписки Прайм Де Люкс.',
	vms_onboarding_settings_hint_title: 'Настройки VK Music Saver',
	vms_onboarding_settings_hint_description: 'В них можно настроить скачивание так, как удобно именно вам',
	vms_sett_single_track_template: 'Формат названия отдельного трека',
	vms_sett_playlist_track_template: 'Формат названия трека в плейлисте',
	vms_sett_audio_write_id3_tags: 'Добавлять ID3 теги к музыке',
	vms_sett_audio_write_id3_tags_desc:
		'Треки и альбомы будут скачиваться с метаданными, такими как имя исполнителя, название, дата выпуска и обложка',
	vms_sett_audio_write_genius_lyrics: 'Вставлять в метаданные треков тексты из Genius',
	vms_sett_audio_write_genius_lyrics_desc:
		'VK Music Saver не связан с этим сайтом и не несет ответственности за точность текстов песен',
	vms_sett_show_bitrate_near_duration: 'Показывать битрейт трека возле длительности',
	vms_alert_rating_title: 'Вам нравится VK Music Saver?',
	vms_alert_rating_desc: 'Пожалуйста, поддержите расширение в рейтинге {storeName}',
	vms_alert_rating_yes: 'Оценить расширение',
	vms_alert_donate_title: 'Поддержите разработчиков',
	vms_alert_donate_desc:
		'VK Music Saver создаётся на энтузиазме — бесплатно, без рекламы, без скрытых сборов данных и с открытым исходным кодом. Если расширение вам нравится, поддержите нас донатом',
	vms_alert_donate_yes: 'Поддержать',
	vms_alert_base_no: 'Нет, спасибо',
	vms_sett_download_playlist_in_reverse: 'Скачивать плейлисты в обратном порядке — с последнего трека к первому',
	vms_vmk_warning_title: 'Расширение не работает в мобильной версии сайта',
	vms_vmk_warning_go_vkcom: 'Перейти на компьютерную версию сайта',
	vms_vmk_warning_hide: 'Не показывать снова',
	vms_sett_add_leading_zeros: 'Форматировать номера треков с ведущими нулями',
	vms_sett_add_leading_zeros_desc: 'Например: 01, 02, 03 … вместо 1, 2, 3',
	installed_header_title: 'VK Music Saver установлен',
	installed_how_title: 'Как работает расширение:',
	installed_step_1: 'Перейдите в раздел с музыкой по ссылке {vkRuAudio} ({vkComAudio}).',
	installed_step_2: 'Рядом с каждым треком отобразится кнопка скачивания, информация о битрейте и размере трека.',
	installed_step_3: 'Нажмите на кнопку, чтобы скачать трек.',
	installed_reload_notice:
		'Если у вас уже открыт сайт {vkRu} ({vkCom}), нужно перезагрузить вкладку, чтобы расширение заработало.',
	installed_attention: 'Обратите внимание',
	installed_pc_version_only:
		'Расширение работает только в полной версии сайта {vkRu} ({vkCom}). При использовании мобильной версии {mobileVkRu} ({mobileVkCom}), расширение не будет работать.',
	installed_follow_community:
		'Подпишитесь на {vkRuVkNext}. Там оперативно выкладывается важная информация для пользователей расширения!',
	installed_follow_community_link: 'наше сообщество ВКонтакте',
	installed_convert_method_notice_1:
		'Если треки не скачиваются или файл весит 0 байт, скорее всего, возникла ошибка на этапе конвертации.',
	installed_convert_method_notice_2:
		'ВКонтакте отдает музыку в формате m3u8, а расширение конвертирует в привычный mp3.',
	installed_convert_method_notice_3:
		'Попробуйте переключиться на метод FFmpeg в настройках. На разных устройствах и браузерах лучше работают разные методы.',
	installed_convert_method_notice_4:
		'Настройки расширения находятся в меню профиля в правом верхнем углу (там, где ваша аватарка).',
	vms_concurrent_downloads_recommendation:
		'Скачивайте не больше двух плейлистов сразу, иначе браузер может зависнуть',
	vms_settings_need_reload_page: 'Перезагрузите страницу, чтобы изменения вступили в силу',
};

export default lang;
