const lang = {
  vms_download: "Downloaden",
  vms_loading: "Laden...",
  vms_error: "Fout",
  vms_download_cover: "Omslag downloaden",
  vms_download_playlist: "Afspeellijst downloaden",
  vms_downloading: "Downloaden...",
  vms_playlist_is_empty: "Afspeellijst is leeg.",
  vms_playlist_not_found: "Afspeellijst niet gevonden",
  vms_audio_not_found: "VK gaf geen trackinformatie terug",
  vms_audio_url_not_found: "Track link ontbreekt",
  vms_album_cover_not_found: "Dit album heeft geen omslag",
  vms_archivation: "archiveren...",
  vms_fs_music_done: "Muziek downloaden voltooid",
  vms_fs_music_playlist_done: "Afspeellijst downloaden voltooid",
  vms_fs_method_selection: "Kies downloadmethode",
  vms_fs_error_selecting_directory: "Fout: kon map niet selecteren",
  vms_fs_option_zip_title: "ZIP-archief",
  vms_fs_option_zip_description: "Alle bestanden worden naar RAM gedownload en daarna ingepakt. U wordt gevraagd waar op te slaan.",
  vms_fs_option_folder_title: "Direct naar map",
  vms_fs_option_folder_description: "U kiest een locatie voor een nieuwe map waar bestanden direct worden opgeslagen zonder RAM-gebruik.",
  vms_fs_option_unselected_title: "Altijd vragen",
  vms_fs_download_method_title: "Bestand downloadmethode",
  vms_fs_select_zip: "Downloaden",
  vms_fs_select_folder: "Map kiezen",
  vms_fs_select_recommended: "Aanbevolen methode",
  vms_download_all_my_music: "Al mijn muziek downloaden",
  vms_download_all_music: "Alle muziek van deze gebruiker downloaden",
  vms_sett_num_tracks_in_playlist: "Nummers in afspeellijst nummeren",
  vms_sett_save_method_selection: "Geselecteerde methode onthouden",
  vms_sett_save_method_selection_description: "U kunt dit altijd wijzigen in de instellingen",
  vms_playlist_download_auth_required: "U moet ingelogd zijn om afspeellijsten te downloaden",
  vms_download_manager_active_tasks: "Actieve downloads",
  vms_download_manager_finished_tasks: "Voltooide downloads",
  vms_download_manager_save: "Opslaan",
  vms_download_manager_remove: "Verwijderen",
  vms_download_manager_cancel: "Annuleren",
  vms_playlist_track_download_completed: "{trackName} - voltooid",
  vms_playlist_download_completed: `Gedownload {total}`,
  vms_tracks_plurals: ["nummer", "nummers", "nummers"],
  vms_sett_audio_convert_mode_title: "Conversiemethode",
  vms_sett_audio_convert_mode_ffmpeg_desc: "Werkt mogelijk niet op oude systemen.",
  vms_sett_audio_convert_mode_hlsjs_desc: "Kan problemen geven in Firefox.",
  vms_sett_audio_convert_mode_desc: "VK levert tracks in m3u8, extensie converteert naar mp3.",
  vms_sett_audio_convert_mode_vknext: "VK Next Server",
  vms_sett_audio_convert_mode_vknext_desc: "Gebruikt FFmpeg. Beter voor grote lijsten omdat het geen RAM gebruikt. Kan traag zijn bij drukte.",
  vms_settings_title: "VK Music Saver Instellingen",
  vms_settings_review_in_firefox: "Beoordeel in Firefox Add-ons",
  vms_settings_review_in_chrome: "Beoordeel in Chrome Web Store",
  vms_settings_donate: "Steun de ontwikkelaars",
  vms_share: "Delen",
  vms_clear_storage: "Instellingen resetten",
  vms_created_by: "Gemaakt door team {name}",
  vms_link_copied: "Link gekopieerd",
  vms_badges_deluxe_function_warning: "Functie beschikbaar voor Prime Deluxe abonnees.",
  vms_onboarding_settings_hint_title: "VK Music Saver Instellingen",
  vms_onboarding_settings_hint_description: "Hier kunt u het downloaden naar wens aanpassen",
  vms_sett_single_track_template: "Naamformaat enkel nummer",
  vms_sett_playlist_track_template: "Naamformaat afspeellijst nummer",
  vms_sett_audio_write_id3_tags: "ID3-tags toevoegen",
  vms_sett_audio_write_id3_tags_desc: "Tracks krijgen metadata zoals artiest, titel, datum en omslag",
  vms_sett_audio_write_genius_lyrics: "Genius songteksten toevoegen",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver is niet verbonden met deze site en niet verantwoordelijk voor juistheid",
  vms_sett_show_bitrate_near_duration: "Bitrate tonen naast duur",
  vms_alert_rating_title: "Vindt u VK Music Saver leuk?",
  vms_alert_rating_desc: "Steun ons door te beoordelen in {storeName}",
  vms_alert_rating_yes: "Beoordelen",
  vms_alert_donate_title: "Steun de ontwikkelaars",
  vms_alert_donate_desc: "VK Music Saver is gratis, zonder reclame of tracking. Steun ons met een donatie als u het leuk vindt.",
  vms_alert_donate_yes: "Steunen",
  vms_alert_base_no: "Nee, bedankt",
  vms_sett_download_playlist_in_reverse: "Afspeellijsten omgekeerd downloaden",
  vms_vmk_warning_title: "Extensie werkt niet op mobiele site",
  vms_vmk_warning_go_vkcom: "Ga naar desktopversie",
  vms_vmk_warning_hide: "Niet meer tonen",
  vms_sett_add_leading_zeros: "Nul voorvoegen bij nummers",
  vms_sett_add_leading_zeros_desc: "Bijv: 01, 02… in plaats van 1, 2",
  installed_header_title: "Extensie geïnstalleerd",
  installed_how_title: "Hoe het werkt:",
  installed_step_1: "Ga naar de muzieksectie",
  installed_step_2: "Naast elk nummer verschijnt een downloadknop en bitrate.",
  installed_step_3: "Klik op de knop om te downloaden.",
  installed_reload_notice: "Als {site} al open staat, herlaad de pagina.",
  installed_attention: "Let op",
  installed_pc_version_only: "Werkt alleen op de volledige {site}, niet op m.vk.ru.",
  installed_follow_community: "Abonneer op {link} voor belangrijke updates!",
  installed_follow_community_link: "onze VK community",
  installed_ffmpeg_notice_1: "Als u Firefox gebruikt en downloads falen, ligt het vaak aan ffmpeg.",
  installed_ffmpeg_notice_2: "VK gebruikt m3u8, de extensie converteert naar mp3.",
  installed_ffmpeg_notice_3: "In Firefox gebruikt de extensie FFmpeg op onze site {site}. Als de site down is, werkt conversie niet.",
  installed_ffmpeg_notice_4: "U kunt hls.js proberen in instellingen. Onafhankelijk van onze site, maar instabiel in Firefox.",
  vms_concurrent_downloads_recommendation: "Download niet meer dan twee lijsten tegelijk om vastlopen te voorkomen",
  vms_settings_need_reload_page: "Herlaad de pagina voor wijzigingen"
};
export default lang;