const lang = {
  vms_download: "Download",
  vms_loading: "Loading...",
  vms_error: "Error",
  vms_download_cover: "Download cover",
  vms_download_playlist: "Download playlist",
  vms_downloading: "Downloading...",
  vms_playlist_is_empty: "Playlist is empty.",
  vms_playlist_not_found: "Playlist not found",
  vms_audio_not_found: "Failed to get track data",
  vms_audio_url_not_found: "Track URL missing",
  vms_album_cover_not_found: "This album has no cover",
  vms_fs_music_done: "Music download completed",
  vms_fs_music_playlist_done: "Playlist download completed",
  vms_fs_method_selection: "Select download method",
  vms_fs_error_selecting_directory: "Error: failed to select save folder",
  vms_fs_option_zip_title: "ZIP archive",
  vms_fs_option_zip_description: "Download as a single file. Archiving occurs during the download process without straining the system.",
  vms_fs_option_folder_title: "Directly to folder",
  vms_fs_option_folder_description: "You are prompted to choose a location to create a new folder where files will be downloaded directly to disk.",
  vms_fs_option_unselected_title: "Always ask",
  vms_fs_download_method_title: "File download method",
  vms_fs_select_zip: "Download",
  vms_fs_select_folder: "Select folder",
  vms_download_all_my_music: "Download all my tracks",
  vms_download_all_music: "Download all tracks of this user",
  vms_sett_num_tracks_in_playlist: "Number tracks in playlist",
  vms_sett_save_method_selection: "Remember selected download method",
  vms_sett_save_method_selection_description: "You can always change the method in extension settings",
  vms_playlist_download_auth_required: "You need to log in to download playlists",
  vms_download_manager_active_tasks: "Active downloads",
  vms_download_manager_finished_tasks: "Finished downloads",
  vms_download_manager_save: "Save",
  vms_download_manager_remove: "Remove",
  vms_download_manager_cancel: "Cancel",
  vms_playlist_track_download_completed: "{trackName} — completed",
  vms_playlist_download_completed: `Downloaded {total}`,
  vms_tracks_plurals: ["track", "tracks", "tracks"],
  vms_sett_audio_convert_mode_title: "Track conversion method",
  vms_sett_audio_convert_mode_ffmpeg_desc: "May not work on older systems.",
  vms_sett_audio_convert_mode_desc: "VK provides tracks in m3u8 format, and the extension converts them to standard mp3.",
  vms_sett_audio_convert_mode_vknext: "VK Next Server",
  vms_sett_audio_convert_mode_vknext_desc: "Uses FFmpeg on the server. Ideal for large playlists as it does not load your processor. Speed may decrease under high server load.",
  vms_settings_title: "VK Music Saver Settings",
  vms_settings_review_in_firefox: "Rate in Firefox Add-ons",
  vms_settings_review_in_chrome: "Rate in Chrome Web Store",
  vms_settings_donate: "Support developers",
  vms_share: "Share",
  vms_clear_storage: "Reset settings",
  vms_clear_track_details_storage: 'Очистить кэш треков',
  vms_clear_track_details_storage_description: 'Размер и битрейт',
  vms_created_by: "Created by {name} team",
  vms_link_copied: "Link copied",
  vms_badges_deluxe_function_warning: "Feature available for Prime Deluxe subscribers.",
  vms_onboarding_settings_hint_title: "VK Music Saver Settings",
  vms_onboarding_settings_hint_description: "Here you can configure downloading to suit your needs",
  vms_sett_single_track_template: "Single track name format",
  vms_sett_playlist_track_template: "Playlist track name format",
  vms_sett_audio_write_id3_tags: "Add ID3 tags to music",
  vms_sett_audio_write_id3_tags_desc: "Tracks and albums will be downloaded with metadata like artist name, title, release date, and cover art",
  vms_sett_audio_write_genius_lyrics: "Embed Genius lyrics into track metadata",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver is not affiliated with this site and is not responsible for lyrics accuracy",
  vms_sett_show_bitrate_near_duration: "Show track bitrate near duration",
  vms_alert_rating_title: "Do you like VK Music Saver?",
  vms_alert_rating_desc: "Please support the extension by rating it in {storeName}",
  vms_alert_rating_yes: "Rate extension",
  vms_alert_donate_title: "Support developers",
  vms_alert_donate_desc: "VK Music Saver is created on enthusiasm — free, no ads, no hidden data collection, and open source. If you like the extension, support us with a donation.",
  vms_alert_donate_yes: "Support",
  vms_alert_base_no: "No, thanks",
  vms_sett_download_playlist_in_reverse: "Download playlists in reverse order — from last track to first",
  vms_vmk_warning_title: "Extension does not work on mobile site version",
  vms_vmk_warning_go_vkcom: "Go to desktop version",
  vms_vmk_warning_hide: "Do not show again",
  vms_sett_add_leading_zeros: "Format track numbers with leading zeros",
  vms_sett_add_leading_zeros_desc: "Example: 01, 02, 03 … instead of 1, 2, 3",
  installed_header_title: "VK Music Saver installed",
  installed_how_title: "How the extension works:",
  installed_step_1: "Go to the music section via the link {vkRuAudio} ({vkComAudio}).",
  installed_step_2: "A download button, bitrate information, and track size will appear next to each track.",
  installed_step_3: "Click the button to download the track.",
  installed_reload_notice: "If you already have the site {vkRu} ({vkCom}) open, you need to reload the tab for the extension to work.",
  installed_attention: "Attention",
  installed_pc_version_only: "The extension works only on the desktop version of the site {vkRu} ({vkCom}). It will not work when using the mobile version {mobileVkRu} ({mobileVkCom}).",
  installed_follow_community: "Subscribe to {vkRuVkNext}. Important information for extension users is promptly posted there!",
  installed_follow_community_link: "our VK community",
  installed_convert_method_notice_1: "If tracks are not downloading or the file size is 0 bytes, an error likely occurred during the conversion stage.",
  installed_convert_method_notice_2: "VKontakte provides music in m3u8 format, and the extension converts it to the familiar mp3.",
  installed_convert_method_notice_3: "Try switching to the FFmpeg method in the settings. Different methods work better on different devices and browsers.",
  installed_convert_method_notice_4: "The extension settings are located in the profile menu in the top right corner (where your avatar is).",
  vms_concurrent_downloads_recommendation: "Do not download more than two playlists at once, otherwise the browser may freeze",
  vms_settings_need_reload_page: "Reload the page for changes to take effect"
};
export default lang;