const lang = {
  vms_download: "Download",
  vms_loading: "Loading...",
  vms_error: "Error",
  vms_download_cover: "Download cover",
  vms_download_playlist: "Download playlist",
  vms_downloading: "Downloading...",
  vms_playlist_is_empty: "Playlist is empty.",
  vms_playlist_not_found: "Playlist not found",
  vms_audio_not_found: "VKontakte did not return the track information",
  vms_audio_url_not_found: "Missing track link",
  vms_album_cover_not_found: "This album doesn't have a cover",
  vms_archivation: "archiving...",
  vms_fs_music_done: "Music download completed",
  vms_fs_music_playlist_done: "Playlist download completed",
  vms_fs_method_selection: "Choose a method to download files",
  vms_fs_error_selecting_directory: "Error: Could not select a folder for saving",
  vms_fs_option_zip_title: "zip-archive",
  vms_fs_option_zip_description: "All files will be loaded into memory and then packed into an archive. You will be prompted to choose where to save it.",
  vms_fs_option_folder_title: "Directly to folder",
  vms_fs_option_folder_description: "You will be prompted to choose a location where a new folder will be created, and files will be saved directly there without using memory.",
  vms_fs_option_unselected_title: "Always ask",
  vms_fs_download_method_title: "Files download method",
  vms_fs_select_zip: "Download",
  vms_fs_select_folder: "Pick a folder",
  vms_fs_select_recommended: "Recommended method",
  vms_download_all_my_music: "Download all my tracks",
  vms_download_all_music: "Download all tracks of this user",
  vms_sett_num_tracks_in_playlist: "Number tracks in playlist",
  vms_sett_save_method_selection: "Remember selected download method",
  vms_sett_save_method_selection_description: "You can always change this in the extension settings",
  vms_playlist_download_auth_required: "You must be authorized to download playlists",
  vms_download_manager_active_tasks: "Active Downloads",
  vms_download_manager_finished_tasks: "Finished downloads",
  vms_download_manager_save: "Save",
  vms_download_manager_remove: "Remove",
  vms_download_manager_cancel: "Cancel",
  vms_playlist_track_download_completed: "{trackName} - completed",
  vms_playlist_download_completed: `Downloaded {total}`,
  vms_tracks_plurals: ["track", "tracks", "tracks"],
  vms_sett_audio_convert_mode_title: "Track conversion method",
  vms_sett_audio_convert_mode_ffmpeg_desc: "May not work on older systems.",
  vms_sett_audio_convert_mode_hlsjs_desc: "May have issues in Firefox.",
  vms_sett_audio_convert_mode_desc: "VK provides tracks in m3u8 format, the extension converts them to standard mp3",
  vms_sett_audio_convert_mode_vknext: "VK Next Server",
  vms_sett_audio_convert_mode_vknext_desc: "Uses FFmpeg for conversion. Best suited for large playlists as it doesn't use RAM for conversion. Might be slow if used by many users at the same time.",
  vms_settings_title: "VK Music Saver Settings",
  vms_settings_review_in_firefox: "Rate us on Firefox Add-ons",
  vms_settings_review_in_chrome: "Rate us on Chrome Web Store",
  vms_settings_donate: "Support the developers",
  vms_share: "Share",
  vms_clear_storage: "Reset settings",
  vms_created_by: "Created by the {name} team",
  vms_link_copied: "Link copied",
  vms_badges_deluxe_function_warning: "The function is available to Prime Deluxe subscribers.",
  vms_onboarding_settings_hint_title: "VK Music Saver Settings",
  vms_onboarding_settings_hint_description: "Here you can customize downloading to your preferences",
  vms_sett_single_track_template: "Single track filename format",
  vms_sett_playlist_track_template: "Playlist track filename format",
  vms_sett_audio_write_id3_tags: "Add ID3 tags to music",
  vms_sett_audio_write_id3_tags_desc: "Tracks and albums will be downloaded with metadata such as artist name, title, release date and artwork",
  vms_sett_audio_write_genius_lyrics: "Insert lyrics into track metadata with Genius",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver is not affiliated with this site and is not responsible for the accuracy of lyrics",
  vms_alert_rating_title: "Do you like VK Music Saver?",
  vms_alert_rating_desc: "Please support the extension on {storeName}",
  vms_alert_rating_yes: "Rate the extension",
  vms_alert_donate_title: "Support the developers",
  vms_alert_donate_desc: 'VK Music Saver создаётся на энтузиазме — бесплатно, без рекламы, без скрытых сборов данных и с открытым исходным кодом. Если расширение вам нравится, поддержите нас донатом',
  vms_alert_donate_yes: "Donate",
  vms_alert_base_no: "No, thanks",
  vms_sett_download_playlist_in_reverse: "Download playlists in reverse order - from the last track to the first track",
  vms_vmk_warning_title: "The extension does not work in the mobile version of the site",
  vms_vmk_warning_go_vkcom: "Go to the computer version of the site",
  vms_sett_add_leading_zeros: 'Форматировать номера треков с ведущими нулями',
  vms_sett_add_leading_zeros_desc: 'Например: 01, 02, 03 … вместо 1, 2, 3'
};
export default lang;