const lang = {
  vms_download: "Herunterladen",
  vms_loading: "Laden...",
  vms_error: "Fehler",
  vms_download_cover: "Cover herunterladen",
  vms_download_playlist: "Playlist herunterladen",
  vms_downloading: "Wird heruntergeladen...",
  vms_playlist_is_empty: "Die Playlist ist leer.",
  vms_playlist_not_found: "Playlist nicht gefunden",
  vms_audio_not_found: 'Не удалось получить данные о треке',
  vms_audio_url_not_found: "Kein Link zum Titel vorhanden",
  vms_album_cover_not_found: "Dieses Album hat kein Cover",
  vms_fs_music_done: "Musik-Download abgeschlossen",
  vms_fs_music_playlist_done: "Playlist-Download abgeschlossen",
  vms_fs_method_selection: "Wählen Sie die Download-Methode",
  vms_fs_error_selecting_directory: "Fehler: Speicherordner konnte nicht ausgewählt werden",
  vms_fs_option_zip_title: "ZIP-Archiv",
  vms_fs_option_zip_description: 'Скачивание одним файлом. Архивация происходит в процессе скачивания без нагрузки на систему.',
  vms_fs_option_folder_title: "Direkt in den Ordner",
  vms_fs_option_folder_description: 'Вам предложен выбор места для создания новой папки, в которую загрузятся файлы напрямую на диск.',
  vms_fs_option_unselected_title: "Immer fragen",
  vms_fs_download_method_title: "Download-Methode",
  vms_fs_select_zip: "Herunterladen",
  vms_fs_select_folder: "Ordner auswählen",
  vms_download_all_my_music: "Alle meine Titel herunterladen",
  vms_download_all_music: "Alle Titel dieses Nutzers herunterladen",
  vms_sett_num_tracks_in_playlist: "Titel in der Playlist nummerieren",
  vms_sett_save_method_selection: "Gewählte Download-Methode merken",
  vms_sett_save_method_selection_description: "Sie können die Methode jederzeit in den Erweiterungseinstellungen ändern",
  vms_playlist_download_auth_required: 'Для скачивания плейлистов необходимо войти в аккаунт',
  vms_download_manager_active_tasks: "Aktive Downloads",
  vms_download_manager_finished_tasks: "Abgeschlossene Downloads",
  vms_download_manager_save: "Speichern",
  vms_download_manager_remove: "Entfernen",
  vms_download_manager_cancel: "Abbrechen",
  vms_playlist_track_download_completed: '{trackName} — завершено',
  vms_playlist_download_completed: `{total} heruntergeladen`,
  vms_tracks_plurals: ["Titel", "Titel", "Titel"],
  vms_sett_audio_convert_mode_title: "Konvertierungsmethode",
  vms_sett_audio_convert_mode_ffmpeg_desc: "Funktioniert möglicherweise nicht auf älteren Systemen.",
  vms_sett_audio_convert_mode_hlsjs_desc: "Kann in Firefox Probleme verursachen.",
  vms_sett_audio_convert_mode_desc: "VK liefert Titel im m3u8-Format, die Erweiterung konvertiert sie in das gewohnte MP3-Format",
  vms_sett_audio_convert_mode_vknext: "VK Next Server",
  vms_sett_audio_convert_mode_vknext_desc: 'Использует FFmpeg на сервере. Идеально для больших плейлистов так как не нагружает ваш процессор. При высокой нагрузке на сервер скорость может снижаться.',
  vms_settings_title: "Einstellungen von VK Music Saver",
  vms_settings_review_in_firefox: "In Firefox Add-ons bewerten",
  vms_settings_review_in_chrome: "Im Chrome Web Store bewerten",
  vms_settings_donate: "Entwickler unterstützen",
  vms_share: "Teilen",
  vms_clear_storage: "Einstellungen zurücksetzen",
  vms_created_by: "Erstellt vom Team {name}",
  vms_link_copied: "Link kopiert",
  vms_badges_deluxe_function_warning: "Funktion verfügbar für Inhaber des Prime Deluxe Abonnements.",
  vms_onboarding_settings_hint_title: "VK Music Saver Einstellungen",
  vms_onboarding_settings_hint_description: "Hier können Sie den Download so anpassen, wie es für Sie am bequemsten ist",
  vms_sett_single_track_template: "Namensformat für Einzeltracks",
  vms_sett_playlist_track_template: "Namensformat für Tracks in Playlists",
  vms_sett_audio_write_id3_tags: "ID3-Tags zur Musik hinzufügen",
  vms_sett_audio_write_id3_tags_desc: "Titel und Alben werden mit Metadaten wie Interpret, Titel, Erscheinungsjahr und Cover heruntergeladen",
  vms_sett_audio_write_genius_lyrics: "Songtexte von Genius in Metadaten einfügen",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver ist nicht mit dieser Website verbunden und nicht verantwortlich für die Richtigkeit der Songtexte",
  vms_sett_show_bitrate_near_duration: "Bitrate neben der Dauer anzeigen",
  vms_alert_rating_title: "Gefällt Ihnen VK Music Saver?",
  vms_alert_rating_desc: "Bitte unterstützen Sie die Erweiterung mit einer Bewertung im {storeName}",
  vms_alert_rating_yes: "Erweiterung bewerten",
  vms_alert_donate_title: "Unterstützen Sie die Entwickler",
  vms_alert_donate_desc: "VK Music Saver wird aus Enthusiasmus entwickelt — kostenlos, ohne Werbung, ohne versteckte Datensammlung und Open Source. Wenn Ihnen die Erweiterung gefällt, unterstützen Sie uns mit einer Spende",
  vms_alert_donate_yes: "Unterstützen",
  vms_alert_base_no: "Nein, danke",
  vms_sett_download_playlist_in_reverse: "Playlists in umgekehrter Reihenfolge herunterladen — vom letzten Titel zum ersten",
  vms_vmk_warning_title: "Die Erweiterung funktioniert nicht in der mobilen Version der Website",
  vms_vmk_warning_go_vkcom: "Zur Desktop-Version wechseln",
  vms_vmk_warning_hide: "Nicht wieder anzeigen",
  vms_sett_add_leading_zeros: "Titelnummern mit führenden Nullen formatieren",
  vms_sett_add_leading_zeros_desc: "Beispiel: 01, 02, 03 … statt 1, 2, 3",
  installed_header_title: 'VK Music Saver установлен',
  installed_how_title: "So funktioniert die Erweiterung:",
  installed_step_1: 'Перейдите в раздел с музыкой по ссылке {vkRuAudio} ({vkComAudio}).',
  installed_step_2: 'Рядом с каждым треком отобразится кнопка скачивания, информация о битрейте и размере трека.',
  installed_step_3: "Klicken Sie auf den Button, um den Titel herunterzuladen.",
  installed_reload_notice: 'Если у вас уже открыт сайт {vkRu} ({vkCom}), нужно перезагрузить вкладку, чтобы расширение заработало.',
  installed_attention: "Bitte beachten",
  installed_pc_version_only: 'Расширение работает только в полной версии сайта {vkRu} ({vkCom}). При использовании мобильной версии {mobileVkRu} ({mobileVkCom}), расширение не будет работать.',
  installed_follow_community: 'Подпишитесь на {vkRuVkNext}. Там оперативно выкладывается важная информация для пользователей расширения!',
  installed_follow_community_link: "unsere VK-Community",
  installed_convert_method_notice_1: 'Если треки не скачиваются или файл весит 0 байт, скорее всего, возникла ошибка на этапе конвертации.',
  installed_convert_method_notice_2: 'ВКонтакте отдает музыку в формате m3u8, а расширение конвертирует в привычный mp3.',
  installed_convert_method_notice_3: 'Попробуйте переключиться на метод FFmpeg в настройках. На разных устройствах и браузерах лучше работают разные методы.',
  installed_convert_method_notice_4: 'Настройки расширения находятся в меню профиля в правом верхнем углу (там, где ваша аватарка).',
  vms_concurrent_downloads_recommendation: "Laden Sie nicht mehr als zwei Playlists gleichzeitig herunter, da der Browser sonst einfrieren kann",
  vms_settings_need_reload_page: "Laden Sie die Seite neu, damit die Änderungen wirksam werden"
};
export default lang;