const lang = {
  vms_download: "Herunterladen",
  vms_loading: "Laden...",
  vms_error: "Fehler",
  vms_download_cover: "Cover herunterladen",
  vms_download_playlist: "Playlist herunterladen",
  vms_downloading: "Wird heruntergeladen...",
  vms_playlist_is_empty: "Die Playlist ist leer.",
  vms_playlist_not_found: "Playlist nicht gefunden",
  vms_audio_not_found: "Track-Daten konnten nicht abgerufen werden",
  vms_audio_url_not_found: "Kein Link zum Titel vorhanden",
  vms_album_cover_not_found: "Dieses Album hat kein Cover",
  vms_fs_music_done: "Musik-Download abgeschlossen",
  vms_fs_music_playlist_done: "Playlist-Download abgeschlossen",
  vms_fs_method_selection: "Wählen Sie die Download-Methode",
  vms_fs_error_selecting_directory: "Fehler: Speicherordner konnte nicht ausgewählt werden",
  vms_fs_option_zip_title: "ZIP-Archiv",
  vms_fs_option_zip_description: "Download als einzelne Datei. Die Archivierung erfolgt während des Downloads, ohne das System zu belasten.",
  vms_fs_option_folder_title: "Direkt in den Ordner",
  vms_fs_option_folder_description: "Sie werden aufgefordert, einen Speicherort für einen neuen Ordner auszuwählen, in den die Dateien direkt auf die Festplatte heruntergeladen werden.",
  vms_fs_option_unselected_title: "Immer fragen",
  vms_fs_download_method_title: "Download-Methode",
  vms_fs_select_zip: "Herunterladen",
  vms_fs_select_folder: "Ordner auswählen",
  vms_download_all_my_music: "Alle meine Titel herunterladen",
  vms_download_all_music: "Alle Titel dieses Nutzers herunterladen",
  vms_sett_num_tracks_in_playlist: "Titel in der Playlist nummerieren",
  vms_sett_save_method_selection: "Gewählte Download-Methode merken",
  vms_sett_save_method_selection_description: "Sie können die Methode jederzeit in den Erweiterungseinstellungen ändern",
  vms_playlist_download_auth_required: "Um Playlists herunterzuladen, müssen Sie sich anmelden",
  vms_download_manager_active_tasks: "Aktive Downloads",
  vms_download_manager_finished_tasks: "Abgeschlossene Downloads",
  vms_download_manager_save: "Speichern",
  vms_download_manager_remove: "Entfernen",
  vms_download_manager_cancel: "Abbrechen",
  vms_playlist_track_download_completed: "{trackName} — abgeschlossen",
  vms_playlist_download_completed: `{total} heruntergeladen`,
  vms_tracks_plurals: ["Titel", "Titel", "Titel"],
  vms_sett_audio_convert_mode_title: "Konvertierungsmethode",
  vms_sett_audio_convert_mode_ffmpeg_desc: "Funktioniert möglicherweise nicht auf älteren Systemen.",
  vms_sett_audio_convert_mode_desc: "VK liefert Titel im m3u8-Format, die Erweiterung konvertiert sie in das gewohnte MP3-Format",
  vms_sett_audio_convert_mode_vknext: "VK Next Server",
  vms_sett_audio_convert_mode_vknext_desc: "Verwendet FFmpeg auf dem Server. Ideal für große Playlists, da Ihr Prozessor nicht belastet wird. Bei hoher Serverlast kann die Geschwindigkeit sinken.",
  vms_settings_title: "Einstellungen von VK Music Saver",
  vms_settings_review_in_firefox: "In Firefox Add-ons bewerten",
  vms_settings_review_in_chrome: "Im Chrome Web Store bewerten",
  vms_settings_donate: "Entwickler unterstützen",
  vms_share: "Teilen",
  vms_clear_storage: "Einstellungen zurücksetzen",
  vms_clear_track_details_storage: 'Очистить кэш треков',
  vms_clear_track_details_storage_description: 'Размер и битрейт',
  vms_created_by: "Erstellt vom Team {name}",
  vms_link_copied: "Link kopiert",
  vms_badges_deluxe_function_warning: "Funktion verfügbar für Inhaber des Prime Deluxe Abonnements.",
  vms_onboarding_settings_hint_title: "VK Music Saver Einstellungen",
  vms_onboarding_settings_hint_description: "Hier können Sie den Download so anpassen, wie es für Sie am bequemsten ist",
  vms_sett_single_track_template: "Namensformat für Einzeltracks",
  vms_sett_playlist_track_template: "Namensformat für Tracks in Playlists",
  vms_sett_audio_write_id3_tags: "ID3-Tags zur Musik hinzufügen",
  vms_sett_audio_write_id3_tags_desc: "Titel und Alben werden mit Metadaten wie Interpret, Titel, Erscheinungsjahr und Cover heruntergeladen",
  vms_sett_audio_write_genius_lyrics: "Songtexte von Genius in Metadaten einfügen",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver ist nicht mit dieser Website verbunden und nicht verantwortlich für die Richtigkeit der Songtexte",
  vms_sett_show_bitrate_near_duration: "Bitrate neben der Dauer anzeigen",
  vms_alert_rating_title: "Gefällt Ihnen VK Music Saver?",
  vms_alert_rating_desc: "Bitte unterstützen Sie die Erweiterung mit einer Bewertung im {storeName}",
  vms_alert_rating_yes: "Erweiterung bewerten",
  vms_alert_donate_title: "Unterstützen Sie die Entwickler",
  vms_alert_donate_desc: "VK Music Saver wird aus Enthusiasmus entwickelt — kostenlos, ohne Werbung, ohne versteckte Datensammlung und Open Source. Wenn Ihnen die Erweiterung gefällt, unterstützen Sie uns mit einer Spende",
  vms_alert_donate_yes: "Unterstützen",
  vms_alert_base_no: "Nein, danke",
  vms_sett_download_playlist_in_reverse: "Playlists in umgekehrter Reihenfolge herunterladen — vom letzten Titel zum ersten",
  vms_vmk_warning_title: "Die Erweiterung funktioniert nicht in der mobilen Version der Website",
  vms_vmk_warning_go_vkcom: "Zur Desktop-Version wechseln",
  vms_vmk_warning_hide: "Nicht wieder anzeigen",
  vms_sett_add_leading_zeros: "Titelnummern mit führenden Nullen formatieren",
  vms_sett_add_leading_zeros_desc: "Beispiel: 01, 02, 03 … statt 1, 2, 3",
  vms_concurrent_downloads_recommendation: "Laden Sie nicht mehr als zwei Playlists gleichzeitig herunter, da der Browser sonst einfrieren kann",
  vms_settings_need_reload_page: "Laden Sie die Seite neu, damit die Änderungen wirksam werden"
};
export default lang;