const lang = {
  vms_download: "डाउनलोड करें",
  vms_loading: "लोड हो रहा है...",
  vms_error: "त्रुटि",
  vms_download_cover: "कवर डाउनलोड करें",
  vms_download_playlist: "प्लेलिस्ट डाउनलोड करें",
  vms_downloading: "डाउनलोड हो रहा है...",
  vms_playlist_is_empty: "प्लेलिस्ट खाली है.",
  vms_playlist_not_found: "प्लेलिस्ट नहीं मिली",
  vms_audio_not_found: 'Не удалось получить данные о треке',
  vms_audio_url_not_found: "ट्रैक का लिंक मौजूद नहीं है",
  vms_album_cover_not_found: "इस एल्बम का कोई कवर नहीं है",
  vms_fs_music_done: "संगीत डाउनलोड पूरा हुआ",
  vms_fs_music_playlist_done: "प्लेलिस्ट डाउनलोड पूरा हुआ",
  vms_fs_method_selection: "फाइल डाउनलोड करने का तरीका चुनें",
  vms_fs_error_selecting_directory: "त्रुटि: सेव करने के लिए फोल्डर नहीं चुना जा सका",
  vms_fs_option_zip_title: "zip-आर्काइव",
  vms_fs_option_zip_description: 'Скачивание одним файлом. Архивация происходит в процессе скачивания без нагрузки на систему.',
  vms_fs_option_folder_title: "सीधे फोल्डर में",
  vms_fs_option_folder_description: 'Вам будет предложен выбор места для создания новой папки, в которую загрузятся файлы напрямую на диск.',
  vms_fs_option_unselected_title: "हमेशा पूछें",
  vms_fs_download_method_title: "फाइल डाउनलोड करने का तरीका",
  vms_fs_select_zip: "डाउनलोड करें",
  vms_fs_select_folder: "फोल्डर चुनें",
  vms_download_all_my_music: "मेरे सभी ट्रैक डाउनलोड करें",
  vms_download_all_music: "इस उपयोगकर्ता के सभी ट्रैक डाउनलोड करें",
  vms_sett_num_tracks_in_playlist: "प्लेलिस्ट में ट्रैक को क्रमांकित करें",
  vms_sett_save_method_selection: "चुने गए डाउनलोड तरीके को याद रखें",
  vms_sett_save_method_selection_description: "आप इसे हमेशा एक्सटेंशन सेटिंग्स में बदल सकते हैं",
  vms_playlist_download_auth_required: 'Для скачивания плейлистов необходимо войти в аккаунт',
  vms_download_manager_active_tasks: "सक्रिय डाउनलोड",
  vms_download_manager_finished_tasks: "पूर्ण डाउनलोड",
  vms_download_manager_save: "सेव करें",
  vms_download_manager_remove: "हटाएँ",
  vms_download_manager_cancel: "रद्द करें",
  vms_playlist_track_download_completed: "{trackName} — पूरा हुआ",
  vms_playlist_download_completed: `डाउनलोड किया गया {total}`,
  vms_tracks_plurals: ["ट्रैक", "ट्रैक", "ट्रैक"],
  vms_sett_audio_convert_mode_title: "ट्रैक कंवर्ज़न का तरीका",
  vms_sett_audio_convert_mode_ffmpeg_desc: "पुराने सिस्टम पर शायद काम न करे।",
  vms_sett_audio_convert_mode_desc: "VK ट्रैक m3u8 फॉर्मेट में देता है, और एक्सटेंशन उसे सामान्य mp3 में बदल देता है",
  vms_sett_audio_convert_mode_vknext: "VK Next सर्वर",
  vms_sett_audio_convert_mode_vknext_desc: 'Использует FFmpeg на сервере. Идеально для больших плейлистов так как не нагружает ваш процессор. При высокой нагрузке на сервер скорость может снижаться.',
  vms_settings_title: "VK Music Saver सेटिंग्स",
  vms_settings_review_in_firefox: "Firefox Add-ons में रेट करें",
  vms_settings_review_in_chrome: "Chrome Web Store में रेट करें",
  vms_settings_donate: "डेवलपर्स का समर्थन करें",
  vms_share: "शेयर करें",
  vms_clear_storage: "सेटिंग्स रीसेट करें",
  vms_clear_track_details_storage: 'Очистить кэш треков',
  vms_clear_track_details_storage_description: 'Размер и битрейт',
  vms_created_by: "{name} टीम द्वारा निर्मित",
  vms_link_copied: "लिंक कॉपी किया गया",
  vms_badges_deluxe_function_warning: "यह फ़ीचर Prime Deluxe सब्सक्राइबर्स के लिए उपलब्ध है।",
  vms_onboarding_settings_hint_title: "VK Music Saver सेटिंग्स",
  vms_onboarding_settings_hint_description: "यहाँ आप अपनी सुविधानुसार डाउनलोडिंग कॉन्फ़िगर कर सकते हैं",
  vms_sett_single_track_template: "एकल ट्रैक नाम का प्रारूप",
  vms_sett_playlist_track_template: "प्लेलिस्ट ट्रैक नाम का प्रारूप",
  vms_sett_audio_write_id3_tags: "संगीत में ID3 टैग जोड़ें",
  vms_sett_audio_write_id3_tags_desc: "ट्रैक और एल्बम मेटाडेटा (जैसे कलाकार, शीर्षक, रिलीज़ की तारीख और कवर) के साथ डाउनलोड होंगे",
  vms_sett_audio_write_genius_lyrics: "ट्रैक मेटाडेटा में Genius से गीत के बोल डालें",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver इस साइट से संबद्ध नहीं है और गीतों की सटीकता के लिए जिम्मेदार नहीं है",
  vms_sett_show_bitrate_near_duration: "अवधि के पास ट्रैक का बिटरेट दिखाएं",
  vms_alert_rating_title: "क्या आपको VK Music Saver पसंद है?",
  vms_alert_rating_desc: "कृपया {storeName} में रेटिंग देकर एक्सटेंशन का समर्थन करें",
  vms_alert_rating_yes: "एक्सटेंशन को रेट करें",
  vms_alert_donate_title: "डेवलपर्स का समर्थन करें",
  vms_alert_donate_desc: "VK Music Saver उत्साह पर बनाया गया है — मुफ्त, बिना विज्ञापन, बिना गुप्त डेटा संग्रह और ओपन सोर्स। यदि आपको एक्सटेंशन पसंद है, तो डोनेट करके हमारा समर्थन करें।",
  vms_alert_donate_yes: "समर्थन करें",
  vms_alert_base_no: "नहीं, धन्यवाद",
  vms_sett_download_playlist_in_reverse: "प्लेलिस्ट उल्टे क्रम में डाउनलोड करें — अंतिम ट्रैक से पहले तक",
  vms_vmk_warning_title: "एक्सटेंशन साइट के मोबाइल संस्करण में काम नहीं करता है",
  vms_vmk_warning_go_vkcom: "साइट के डेस्कटॉप संस्करण पर जाएं",
  vms_vmk_warning_hide: "दोबारा न दिखाएं",
  vms_sett_add_leading_zeros: "ट्रैक नंबरों को लीडिंग ज़ीरो के साथ फॉर्मेट करें",
  vms_sett_add_leading_zeros_desc: "उदाहरण: 1, 2, 3 के बजाय 01, 02, 03 …",
  installed_header_title: "VK Music Saver इंस्टॉल हो गया है",
  installed_how_title: "एक्सटेंशन कैसे काम करता है:",
  installed_step_1: 'Перейдите в раздел с музыкой по ссылке {vkRuAudio} ({vkComAudio}).',
  installed_step_2: 'Рядом с каждым треком отобразится кнопка скачивания, информация о битрейте и размере трека.',
  installed_step_3: "ट्रैक डाउनलोड करने के लिए बटन पर क्लिक करें।",
  installed_reload_notice: 'Если у вас уже открыт сайт {vkRu} ({vkCom}), нужно перезагрузить вкладку, чтобы расширение заработало.',
  installed_attention: "ध्यान दें",
  installed_pc_version_only: 'Расширение работает только в полной версии сайта {vkRu} ({vkCom}). При использовании мобильной версии {mobileVkRu} ({mobileVkCom}), расширение не будет работать.',
  installed_follow_community: 'Подпишитесь на {vkRuVkNext}. Там оперативно выкладывается важная информация для пользователей расширения!',
  installed_follow_community_link: "हमारा VK समुदाय",
  installed_convert_method_notice_1: 'Если треки не скачиваются или файл весит 0 байт, скорее всего, возникла ошибка на этапе конвертации.',
  installed_convert_method_notice_2: 'ВКонтакте отдает музыку в формате m3u8, а расширение конвертирует в привычный mp3.',
  installed_convert_method_notice_3: 'Попробуйте переключиться на метод FFmpeg в настройках. На разных устройствах и браузерах лучше работают разные методы.',
  installed_convert_method_notice_4: 'Настройки расширения находятся в меню профиля в правом верхнем углу (там, где ваша аватарка).',
  vms_concurrent_downloads_recommendation: "एक साथ दो से अधिक प्लेलिस्ट डाउनलोड न करें, अन्यथा ब्राउज़र फ्रीज हो सकता है",
  vms_settings_need_reload_page: "बदलावों को लागू करने के लिए पेज को रीलोड करें"
};
export default lang;