const lang = {
	vms_download: 'Жүктеп алу',
	vms_loading: 'Жүктелуде...',
	vms_error: 'Қате',
	vms_download_cover: 'Мұқабаны жүктеп алу',
	vms_download_playlist: 'Плейлистті жүктеп алу',
	vms_downloading: 'Жүктелуде...',
	vms_playlist_is_empty: 'Плейлист бос.',
	vms_playlist_not_found: 'Плейлист табылмады',
	vms_audio_not_found: 'Не удалось получить данные о треке',
	vms_audio_url_not_found: 'Трек сілтемесі жоқ',
	vms_album_cover_not_found: 'Бұл альбомның мұқабасы жоқ',
	vms_fs_music_done: 'Музыканы жүктеу аяқталды',
	vms_fs_music_playlist_done: 'Плейлистті жүктеу аяқталды',
	vms_fs_method_selection: 'Файлдарды жүктеу әдісін таңдаңыз',
	vms_fs_error_selecting_directory: 'Қате: сақтау қалтасын таңдау мүмкін болмады',
	vms_fs_option_zip_title: 'zip-архив',
	vms_fs_option_zip_description:
		'Скачивание одним файлом. Архивация происходит в процессе скачивания без нагрузки на систему.',
	vms_fs_option_folder_title: 'Тікелей қалтаға',
	vms_fs_option_folder_description:
		'Вам будет предложен выбор места для создания новой папки, в которую загрузятся файлы напрямую на диск.',
	vms_fs_option_unselected_title: 'Әрқашан сұрау',
	vms_fs_download_method_title: 'Файлдарды жүктеу әдісі',
	vms_fs_select_zip: 'Жүктеп алу',
	vms_fs_select_folder: 'Қалтаны таңдау',
	vms_download_all_my_music: 'Барлық тректерімді жүктеп алу',
	vms_download_all_music: 'Осы пайдаланушының барлық тректерін жүктеп алу',
	vms_sett_num_tracks_in_playlist: 'Плейлисттегі тректерді нөмірлеу',
	vms_sett_save_method_selection: 'Таңдалған жүктеу әдісін есте сақтау',
	vms_sett_save_method_selection_description: 'Әдісті кез келген уақытта кеңейтім баптауларынан өзгерте аласыз',
	vms_playlist_download_auth_required: 'Для скачивания плейлистов необходимо войти в аккаунт',
	vms_download_manager_active_tasks: 'Белсенді жүктеулер',
	vms_download_manager_finished_tasks: 'Аяқталған жүктеулер',
	vms_download_manager_save: 'Сақтау',
	vms_download_manager_remove: 'Жою',
	vms_download_manager_cancel: 'Болдырмау',
	vms_playlist_track_download_completed: '{trackName} — аяқталды',
	vms_playlist_download_completed: `Жүктелді {total}`,
	vms_tracks_plurals: ['трек', 'трек', 'трек'],
	vms_sett_audio_convert_mode_title: 'Тректерді түрлендіру әдісі',
	vms_sett_audio_convert_mode_ffmpeg_desc: 'Ескі жүйелерде жұмыс істемеуі мүмкін.',
	vms_sett_audio_convert_mode_desc:
		'ВКонтакте тректерді m3u8 форматында береді, ал кеңейтім оларды үйреншікті mp3-ке түрлендіреді',
	vms_sett_audio_convert_mode_vknext: 'VK Next сервері',
	vms_sett_audio_convert_mode_vknext_desc:
		'Использует FFmpeg на сервере. Идеально для больших плейлистов так как не нагружает ваш процессор. При высокой нагрузке на сервер скорость может снижаться.',
	vms_settings_title: 'VK Music Saver баптаулары',
	vms_settings_review_in_firefox: 'Firefox Add-ons-та бағалау',
	vms_settings_review_in_chrome: 'Chrome Web Store-да бағалау',
	vms_settings_donate: 'Әзірлеушілерге қолдау көрсету',
	vms_share: 'Бөлісу',
	vms_clear_storage: 'Баптауларды қайтару',
	vms_clear_track_details_storage: 'Очистить кэш треков',
	vms_clear_track_details_storage_description: 'Размер и битрейт',
	vms_created_by: '{name} командасы жасаған',
	vms_link_copied: 'Сілтеме көшірілді',
	vms_badges_deluxe_function_warning: 'Бұл функция Prime Deluxe жазылымы иелеріне қолжетімді.',
	vms_onboarding_settings_hint_title: 'VK Music Saver баптаулары',
	vms_onboarding_settings_hint_description: 'Мұнда жүктеуді өзіңізге ыңғайлы етіп баптай аласыз',
	vms_sett_single_track_template: 'Жеке трек атауының пішімі',
	vms_sett_playlist_track_template: 'Плейлисттегі трек атауының пішімі',
	vms_sett_audio_write_id3_tags: 'Музыкаға ID3 тегтерін қосу',
	vms_sett_audio_write_id3_tags_desc:
		'Тректер мен альбомдар орындаушы аты, атауы, шыққан жылы және мұқаба сияқты метадеректермен жүктеледі',
	vms_sett_audio_write_genius_lyrics: 'Трек метадеректеріне Genius-тан мәтін кірістіру',
	vms_sett_audio_write_genius_lyrics_desc:
		'VK Music Saver бұл сайтпен байланысты емес және өлең мәтіндерінің дұрыстығына жауап бермейді',
	vms_sett_show_bitrate_near_duration: 'Ұзақтығы жанында трек битрейтін көрсету',
	vms_alert_rating_title: 'VK Music Saver сізге ұнай ма?',
	vms_alert_rating_desc: '{storeName} рейтингінде кеңейтімді қолдауыңызды сұраймыз',
	vms_alert_rating_yes: 'Кеңейтімді бағалау',
	vms_alert_donate_title: 'Әзірлеушілерге қолдау көрсетіңіз',
	vms_alert_donate_desc:
		'VK Music Saver энтузиазммен жасалады — тегін, жарнамасыз, жасырын дерек жинаусыз және ашық бастапқы кодпен. Егер кеңейтім ұнаса, бізді донатпен қолдаңыз',
	vms_alert_donate_yes: 'Қолдау',
	vms_alert_base_no: 'Жоқ, рақмет',
	vms_sett_download_playlist_in_reverse: 'Плейлисттерді кері ретпен жүктеу — соңғы тректен біріншіге қарай',
	vms_vmk_warning_title: 'Кеңейтім сайттың мобильді нұсқасында жұмыс істемейді',
	vms_vmk_warning_go_vkcom: 'Сайттың компьютерлік нұсқасына өту',
	vms_vmk_warning_hide: 'Қайта көрсетпеу',
	vms_sett_add_leading_zeros: 'Трек нөмірлерін алдыңғы нөлдермен пішімдеу',
	vms_sett_add_leading_zeros_desc: 'Мысалы: 1, 2, 3 орнына 01, 02, 03 …',
	vms_concurrent_downloads_recommendation:
		'Бір уақытта екі плейлисттен артық жүктемеңіз, әйтпесе браузер қатып қалуы мүмкін',
	vms_settings_need_reload_page: 'Өзгерістер күшіне енуі үшін парақшаны қайта жүктеңіз',
};
export default lang;
