const lang = {
  vms_download: "Жүктеп алу",
  vms_loading: "Жүктелуде...",
  vms_error: "Қате",
  vms_download_cover: "Мұқабаны жүктеп алу",
  vms_download_playlist: "Плейлистті жүктеп алу",
  vms_downloading: "Жүктелуде...",
  vms_playlist_is_empty: "Плейлист бос.",
  vms_playlist_not_found: "Плейлист табылмады",
  vms_audio_not_found: "ВКонтакте трек туралы ақпарат қайтармады",
  vms_audio_url_not_found: "Трек сілтемесі жоқ",
  vms_album_cover_not_found: "Бұл альбомның мұқабасы жоқ",
  vms_archivation: "архивтеу...",
  vms_fs_music_done: "Музыканы жүктеу аяқталды",
  vms_fs_music_playlist_done: "Плейлистті жүктеу аяқталды",
  vms_fs_method_selection: "Файлдарды жүктеу әдісін таңдаңыз",
  vms_fs_error_selecting_directory: "Қате: сақтау қалтасын таңдау мүмкін болмады",
  vms_fs_option_zip_title: 'zip-архив',
  vms_fs_option_zip_description: "Барлық файлдар жедел жадыға жүктеліп, кейін мұрағатқа жинақталады, сақтау орны сізге ұсынылады.",
  vms_fs_option_folder_title: "Тікелей қалтаға",
  vms_fs_option_folder_description: "Сізге жаңа қалта құру орнын таңдау ұсынылады, файлдар жедел жадыға алдын ала сақталмастан сол жерге жүктеледі.",
  vms_fs_option_unselected_title: "Әрқашан сұрау",
  vms_fs_download_method_title: "Файлдарды жүктеу әдісі",
  vms_fs_select_zip: "Жүктеп алу",
  vms_fs_select_folder: "Қалтаны таңдау",
  vms_fs_select_recommended: "Ұсынылатын әдіс",
  vms_download_all_my_music: "Барлық тректерімді жүктеп алу",
  vms_download_all_music: "Осы пайдаланушының барлық тректерін жүктеп алу",
  vms_sett_num_tracks_in_playlist: "Плейлисттегі тректерді нөмірлеу",
  vms_sett_save_method_selection: "Таңдалған жүктеу әдісін есте сақтау",
  vms_sett_save_method_selection_description: "Әдісті кез келген уақытта кеңейтім баптауларынан өзгерте аласыз",
  vms_playlist_download_auth_required: "Плейлисттерді жүктеу үшін жүйеге кіруіңіз керек",
  vms_download_manager_active_tasks: "Белсенді жүктеулер",
  vms_download_manager_finished_tasks: "Аяқталған жүктеулер",
  vms_download_manager_save: "Сақтау",
  vms_download_manager_remove: "Жою",
  vms_download_manager_cancel: "Болдырмау",
  vms_playlist_track_download_completed: "{trackName} - аяқталды",
  vms_playlist_download_completed: `Жүктелді {total}`,
  vms_tracks_plurals: ['трек', "трек", "трек"],
  vms_sett_audio_convert_mode_title: "Тректерді түрлендіру әдісі",
  vms_sett_audio_convert_mode_ffmpeg_desc: "Ескі жүйелерде жұмыс істемеуі мүмкін.",
  vms_sett_audio_convert_mode_hlsjs_desc: "Firefox-та қиындықтар туындауы мүмкін.",
  vms_sett_audio_convert_mode_desc: "ВКонтакте тректерді m3u8 форматында береді, ал кеңейтім оларды үйреншікті mp3-ке түрлендіреді",
  vms_sett_audio_convert_mode_vknext: "VK Next сервері",
  vms_sett_audio_convert_mode_vknext_desc: "Түрлендіру үшін FFmpeg қолданады. Үлкен плейлисттерді жүктеуге ең қолайлы, себебі түрлендіру жедел жадыны алмайды. Алайда, бұл әдісті бір уақытта көп қолданушы пайдаланса, баяу жұмыс істеуі мүмкін.",
  vms_settings_title: "VK Music Saver баптаулары",
  vms_settings_review_in_firefox: "Firefox Add-ons-та бағалау",
  vms_settings_review_in_chrome: "Chrome Web Store-да бағалау",
  vms_settings_donate: "Әзірлеушілерге қолдау көрсету",
  vms_share: "Бөлісу",
  vms_clear_storage: "Баптауларды қайтару",
  vms_created_by: "{name} командасы жасаған",
  vms_link_copied: "Сілтеме көшірілді",
  vms_badges_deluxe_function_warning: "Бұл функция Prime Deluxe жазылымы иелеріне қолжетімді.",
  vms_onboarding_settings_hint_title: "VK Music Saver баптаулары",
  vms_onboarding_settings_hint_description: "Мұнда жүктеуді өзіңізге ыңғайлы етіп баптай аласыз",
  vms_sett_single_track_template: "Жеке трек атауының пішімі",
  vms_sett_playlist_track_template: "Плейлисттегі трек атауының пішімі",
  vms_sett_audio_write_id3_tags: "Музыкаға ID3 тегтерін қосу",
  vms_sett_audio_write_id3_tags_desc: "Тректер мен альбомдар орындаушы аты, атауы, шыққан жылы және мұқаба сияқты метадеректермен жүктеледі",
  vms_sett_audio_write_genius_lyrics: "Трек метадеректеріне Genius-тан мәтін кірістіру",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver бұл сайтпен байланысты емес және өлең мәтіндерінің дұрыстығына жауап бермейді",
  vms_sett_show_bitrate_near_duration: "Ұзақтығы жанында трек битрейтін көрсету",
  vms_alert_rating_title: "VK Music Saver сізге ұнай ма?",
  vms_alert_rating_desc: "{storeName} рейтингінде кеңейтімді қолдауыңызды сұраймыз",
  vms_alert_rating_yes: "Кеңейтімді бағалау",
  vms_alert_donate_title: "Әзірлеушілерге қолдау көрсетіңіз",
  vms_alert_donate_desc: "VK Music Saver энтузиазммен жасалады — тегін, жарнамасыз, жасырын дерек жинаусыз және ашық бастапқы кодпен. Егер кеңейтім ұнаса, бізді донатпен қолдаңыз",
  vms_alert_donate_yes: "Қолдау",
  vms_alert_base_no: "Жоқ, рақмет",
  vms_sett_download_playlist_in_reverse: "Плейлисттерді кері ретпен жүктеу — соңғы тректен біріншіге қарай",
  vms_vmk_warning_title: "Кеңейтім сайттың мобильді нұсқасында жұмыс істемейді",
  vms_vmk_warning_go_vkcom: "Сайттың компьютерлік нұсқасына өту",
  vms_vmk_warning_hide: "Қайта көрсетпеу",
  vms_sett_add_leading_zeros: "Трек нөмірлерін алдыңғы нөлдермен пішімдеу",
  vms_sett_add_leading_zeros_desc: "Мысалы: 1, 2, 3 орнына 01, 02, 03 …",
  installed_header_title: "Кеңейтім орнатылды",
  installed_how_title: "Кеңейтім қалай жұмыс істейді:",
  installed_step_1: "Музыка бөліміне өтіңіз",
  installed_step_2: "Әр тректің жанында жүктеу батырмасы мен битрейт туралы ақпарат пайда болады.",
  installed_step_3: "Тректі жүктеу үшін батырманы басыңыз.",
  installed_reload_notice: "Егер сізде {site} сайты ашық болса, кеңейтім жұмыс істеуі үшін қойындыны қайта жүктеу қажет.",
  installed_attention: "Назар аударыңыз",
  installed_pc_version_only: "Кеңейтім тек {site} сайтының толық нұсқасында жұмыс істейді. m.vk.ru мобильді нұсқасын қолданғанда, кеңейтім жұмыс істемейді.",
  installed_follow_community: "{link} жазылыңыз. Ол жерде кеңейтім пайдаланушылары үшін маңызды ақпарат жедел жарияланады!",
  installed_follow_community_link: "біздің ВКонтакте қауымдастығымызға",
  installed_ffmpeg_notice_1: "Егер сізде Firefox болып, тректер жүктелмесе, мәселе ffmpeg-те (тректерді түрлендіру) болуы мүмкін.",
  installed_ffmpeg_notice_2: "ВКонтакте тректерді m3u8 форматында береді, ал кеңейтім оларды үйреншікті mp3-ке түрлендіреді.",
  installed_ffmpeg_notice_3: "Firefox-та кеңейтім әдепкі бойынша біздің {site} сайтымызда орналасқан FFmpeg-ті қолданады. Егер сайт қолжетімсіз болса — түрлендіру жұмыс істемейді және кеңейтім тректі жүктей алмайды.",
  installed_ffmpeg_notice_4: "Кеңейтім баптауларында hls.js әдісіне ауысуға болады. Ол біздің сайтқа тәуелді емес, бірақ Firefox-та тұрақсыз жұмыс істейді — дыбыста сыртыл немесе бұрмалау болуы мүмкін.",
  vms_concurrent_downloads_recommendation: "Бір уақытта екі плейлисттен артық жүктемеңіз, әйтпесе браузер қатып қалуы мүмкін",
  vms_settings_need_reload_page: "Өзгерістер күшіне енуі үшін парақшаны қайта жүктеңіз"
};
export default lang;