const lang = {
  vms_download: "Pobierz",
  vms_loading: "Ładowanie...",
  vms_error: "Błąd",
  vms_download_cover: "Pobierz okładkę",
  vms_download_playlist: "Pobierz playlistę",
  vms_downloading: "Pobieranie...",
  vms_playlist_is_empty: "Playlista jest pusta.",
  vms_playlist_not_found: "Nie znaleziono playlisty",
  vms_audio_not_found: 'Не удалось получить данные о треке',
  vms_audio_url_not_found: "Brak linku do utworu",
  vms_album_cover_not_found: "Ten album nie ma okładki",
  vms_fs_music_done: "Pobieranie muzyki zakończone",
  vms_fs_music_playlist_done: "Pobieranie playlisty zakończone",
  vms_fs_method_selection: "Wybierz sposób pobierania plików",
  vms_fs_error_selecting_directory: "Błąd: nie udało się wybrać folderu do zapisu",
  vms_fs_option_zip_title: "Archiwum zip",
  vms_fs_option_zip_description: 'Скачивание одним файлом. Архивация происходит в процессе скачивания без нагрузки на систему.',
  vms_fs_option_folder_title: "Bezpośrednio do folderu",
  vms_fs_option_folder_description: 'Вам будет предложен выбор места для создания новой папки, в которую загрузятся файлы напрямую на диск.',
  vms_fs_option_unselected_title: "Zawsze pytaj",
  vms_fs_download_method_title: "Sposób pobierania plików",
  vms_fs_select_zip: "Pobierz",
  vms_fs_select_folder: "Wybierz folder",
  vms_download_all_my_music: "Pobierz wszystkie moje utwory",
  vms_download_all_music: "Pobierz wszystkie utwory tego użytkownika",
  vms_sett_num_tracks_in_playlist: "Numeruj utwory na playliście",
  vms_sett_save_method_selection: "Zapamiętaj wybrany sposób pobierania",
  vms_sett_save_method_selection_description: "Zawsze możesz zmienić sposób w ustawieniach rozszerzenia",
  vms_playlist_download_auth_required: 'Для скачивания плейлистов необходимо войти в аккаунт',
  vms_download_manager_active_tasks: "Aktywne pobierania",
  vms_download_manager_finished_tasks: "Zakończone pobierania",
  vms_download_manager_save: "Zapisz",
  vms_download_manager_remove: "Usuń",
  vms_download_manager_cancel: "Anuluj",
  vms_playlist_track_download_completed: '{trackName} — завершено',
  vms_playlist_download_completed: `Pobrano {total}`,
  vms_tracks_plurals: ["utwór", "utwory", "utworów"],
  vms_sett_audio_convert_mode_title: "Metoda konwersji utworów",
  vms_sett_audio_convert_mode_ffmpeg_desc: "Może nie działać na starszych systemach.",
  vms_sett_audio_convert_mode_hlsjs_desc: "W Firefox mogą występować problemy.",
  vms_sett_audio_convert_mode_desc: "VK udostępnia utwory w formacie m3u8, a rozszerzenie konwertuje je do zwykłego mp3",
  vms_sett_audio_convert_mode_vknext: "Serwer VK Next",
  vms_sett_audio_convert_mode_vknext_desc: 'Использует FFmpeg на сервере. Идеально для больших плейлистов так как не нагружает ваш процессор. При высокой нагрузке на сервер скорость может снижаться.',
  vms_settings_title: "Ustawienia VK Music Saver",
  vms_settings_review_in_firefox: "Oceń w Firefox Add-ons",
  vms_settings_review_in_chrome: "Oceń w Chrome Web Store",
  vms_settings_donate: "Wesprzyj twórców",
  vms_share: "Udostępnij",
  vms_clear_storage: "Resetuj ustawienia",
  vms_created_by: "Stworzone przez zespół {name}",
  vms_link_copied: "Link skopiowany",
  vms_badges_deluxe_function_warning: "Funkcja dostępna dla posiadaczy subskrypcji Prime Deluxe.",
  vms_onboarding_settings_hint_title: "Ustawienia VK Music Saver",
  vms_onboarding_settings_hint_description: "Możesz tutaj dostosować pobieranie tak, jak Ci wygodnie",
  vms_sett_single_track_template: "Format nazwy pojedynczego utworu",
  vms_sett_playlist_track_template: "Format nazwy utworu na playliście",
  vms_sett_audio_write_id3_tags: "Dodawaj tagi ID3 do muzyki",
  vms_sett_audio_write_id3_tags_desc: "Utwory i albumy będą pobierane z metadanymi, takimi jak wykonawca, tytuł, data wydania i okładka",
  vms_sett_audio_write_genius_lyrics: "Wstawiaj teksty z Genius do metadanych utworów",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver nie jest powiązany z tą stroną i nie ponosi odpowiedzialności za dokładność tekstów piosenek",
  vms_sett_show_bitrate_near_duration: "Pokazuj bitrate utworu obok czasu trwania",
  vms_alert_rating_title: "Podoba Ci się VK Music Saver?",
  vms_alert_rating_desc: "Prosimy, wesprzyj rozszerzenie w rankingu {storeName}",
  vms_alert_rating_yes: "Oceń rozszerzenie",
  vms_alert_donate_title: "Wesprzyj twórców",
  vms_alert_donate_desc: "VK Music Saver powstaje z entuzjazmu — za darmo, bez reklam, bez ukrytego zbierania danych i z otwartym kodem źródłowym. Jeśli podoba Ci się rozszerzenie, wesprzyj nas dotacją",
  vms_alert_donate_yes: "Wesprzyj",
  vms_alert_base_no: "Nie, dziękuję",
  vms_sett_download_playlist_in_reverse: "Pobieraj playlisty w odwrotnej kolejności — od ostatniego utworu do pierwszego",
  vms_vmk_warning_title: "Rozszerzenie nie działa w mobilnej wersji strony",
  vms_vmk_warning_go_vkcom: "Przejdź do komputerowej wersji strony",
  vms_vmk_warning_hide: "Nie pokazuj ponownie",
  vms_sett_add_leading_zeros: "Formatuj numery utworów z zerami wiodącymi",
  vms_sett_add_leading_zeros_desc: "Na przykład: 01, 02, 03 … zamiast 1, 2, 3",
  installed_header_title: 'VK Music Saver установлен',
  installed_how_title: "Jak działa rozszerzenie:",
  installed_step_1: 'Перейдите в раздел с музыкой по ссылке {vkRuAudio} ({vkComAudio}).',
  installed_step_2: 'Рядом с каждым треком отобразится кнопка скачивания, информация о битрейте и размере трека.',
  installed_step_3: "Kliknij przycisk, aby pobrać utwór.",
  installed_reload_notice: 'Если у вас уже открыт сайт {vkRu} ({vkCom}), нужно перезагрузить вкладку, чтобы расширение заработало.',
  installed_attention: "Zwróć uwagę",
  installed_pc_version_only: 'Расширение работает только в полной версии сайта {vkRu} ({vkCom}). При использовании мобильной версии {mobileVkRu} ({mobileVkCom}), расширение не будет работать.',
  installed_follow_community: 'Подпишитесь на {vkRuVkNext}. Там оперативно выкладывается важная информация для пользователей расширения!',
  installed_follow_community_link: "naszą społeczność VK",
  installed_convert_method_notice_1: 'Если треки не скачиваются или файл весит 0 байт, скорее всего, возникла ошибка на этапе конвертации.',
  installed_convert_method_notice_2: 'ВКонтакте отдает музыку в формате m3u8, а расширение конвертирует в привычный mp3.',
  installed_convert_method_notice_3: 'Попробуйте переключиться на метод FFmpeg в настройках. На разных устройствах и браузерах лучше работают разные методы.',
  installed_convert_method_notice_4: 'Настройки расширения находятся в меню профиля в правом верхнем углу (там, где ваша аватарка).',
  vms_concurrent_downloads_recommendation: "Nie pobieraj więcej niż dwie playlisty jednocześnie, w przeciwnym razie przeglądarka może się zawiesić",
  vms_settings_need_reload_page: "Odśwież stronę, aby zmiany weszły w życie"
};
export default lang;