const lang = {
  vms_download: "Baixar",
  vms_loading: "Carregando...",
  vms_error: "Erro",
  vms_download_cover: "Baixar capa",
  vms_download_playlist: "Baixar playlist",
  vms_downloading: "Baixando...",
  vms_playlist_is_empty: "A playlist está vazia.",
  vms_playlist_not_found: "Playlist não encontrada",
  vms_audio_not_found: "O VK não retornou informações sobre a faixa",
  vms_audio_url_not_found: "Link da faixa ausente",
  vms_album_cover_not_found: "Este álbum não tem capa",
  vms_archivation: "arquivando...",
  vms_fs_music_done: "Download de música concluído",
  vms_fs_music_playlist_done: "Download da playlist concluído",
  vms_fs_method_selection: "Escolha o método de download dos arquivos",
  vms_fs_error_selecting_directory: "Erro: não foi possível selecionar a pasta para salvar",
  vms_fs_option_zip_title: "Arquivo zip",
  vms_fs_option_zip_description: "Todos os arquivos serão carregados na memória RAM e depois compactados em um arquivo, cujo local de salvamento será sugerido a você.",
  vms_fs_option_folder_title: "Diretamente na pasta",
  vms_fs_option_folder_description: "Será solicitado que você escolha um local para criar uma nova pasta, onde os arquivos serão baixados sem salvar previamente na memória RAM.",
  vms_fs_option_unselected_title: "Sempre perguntar",
  vms_fs_download_method_title: "Método de download de arquivos",
  vms_fs_select_zip: "Baixar",
  vms_fs_select_folder: "Escolher pasta",
  vms_fs_select_recommended: "Método recomendado",
  vms_download_all_my_music: "Baixar todas as minhas músicas",
  vms_download_all_music: "Baixar todas as músicas deste usuário",
  vms_sett_num_tracks_in_playlist: "Numerar faixas na playlist",
  vms_sett_save_method_selection: "Lembrar método de download escolhido",
  vms_sett_save_method_selection_description: "Você sempre pode alterar o método nas configurações da extensão",
  vms_playlist_download_auth_required: "Você precisa estar logado para baixar playlists",
  vms_download_manager_active_tasks: "Downloads ativos",
  vms_download_manager_finished_tasks: "Downloads concluídos",
  vms_download_manager_save: "Salvar",
  vms_download_manager_remove: "Remover",
  vms_download_manager_cancel: "Cancelar",
  vms_playlist_track_download_completed: "{trackName} - concluído",
  vms_playlist_download_completed: `Baixado {total}`,
  vms_tracks_plurals: ["faixa", "faixas", "faixas"],
  vms_sett_audio_convert_mode_title: "Método de conversão de faixas",
  vms_sett_audio_convert_mode_ffmpeg_desc: "Pode não funcionar em sistemas antigos.",
  vms_sett_audio_convert_mode_hlsjs_desc: "No Firefox podem ocorrer problemas.",
  vms_sett_audio_convert_mode_desc: "O VK entrega faixas no formato m3u8, e a extensão converte para o habitual mp3",
  vms_sett_audio_convert_mode_vknext: "Servidor VK Next",
  vms_sett_audio_convert_mode_vknext_desc: "Usa FFmpeg para conversão. Melhor para baixar grandes playlists, pois a conversão não ocupa memória RAM. No entanto, pode funcionar lentamente se muitos usuários usarem este método simultaneamente.",
  vms_settings_title: "Configurações do VK Music Saver",
  vms_settings_review_in_firefox: "Avaliar no Firefox Add-ons",
  vms_settings_review_in_chrome: "Avaliar na Chrome Web Store",
  vms_settings_donate: "Apoiar os desenvolvedores",
  vms_share: "Compartilhar",
  vms_clear_storage: "Redefinir configurações",
  vms_created_by: "Criado pela equipe {name}",
  vms_link_copied: "Link copiado",
  vms_badges_deluxe_function_warning: "Função disponível para assinantes Prime Deluxe.",
  vms_onboarding_settings_hint_title: "Configurações do VK Music Saver",
  vms_onboarding_settings_hint_description: "Nelas você pode configurar o download da maneira que for mais conveniente para você",
  vms_sett_single_track_template: "Formato do nome da faixa única",
  vms_sett_playlist_track_template: "Formato do nome da faixa na playlist",
  vms_sett_audio_write_id3_tags: "Adicionar tags ID3 à música",
  vms_sett_audio_write_id3_tags_desc: "Faixas e álbuns serão baixados com metadados, como nome do artista, título, data de lançamento e capa",
  vms_sett_audio_write_genius_lyrics: "Inserir letras do Genius nos metadados das faixas",
  vms_sett_audio_write_genius_lyrics_desc: "O VK Music Saver não é vinculado a este site e não se responsabiliza pela precisão das letras das músicas",
  vms_sett_show_bitrate_near_duration: "Mostrar bitrate da faixa perto da duração",
  vms_alert_rating_title: "Você gosta do VK Music Saver?",
  vms_alert_rating_desc: "Por favor, apoie a extensão na classificação da {storeName}",
  vms_alert_rating_yes: "Avaliar a extensão",
  vms_alert_donate_title: "Apoie os desenvolvedores",
  vms_alert_donate_desc: "O VK Music Saver é criado por entusiasmo — grátis, sem anúncios, sem coleta oculta de dados e com código aberto. Se você gosta da extensão, apoie-nos com uma doação",
  vms_alert_donate_yes: "Apoiar",
  vms_alert_base_no: "Não, obrigado",
  vms_sett_download_playlist_in_reverse: "Baixar playlists na ordem inversa — da última faixa para a primeira",
  vms_vmk_warning_title: "A extensão não funciona na versão móvel do site",
  vms_vmk_warning_go_vkcom: "Ir para a versão desktop do site",
  vms_vmk_warning_hide: "Não mostrar novamente",
  vms_sett_add_leading_zeros: "Formatar números das faixas com zeros à esquerda",
  vms_sett_add_leading_zeros_desc: "Por exemplo: 01, 02, 03 … em vez de 1, 2, 3",
  installed_header_title: "Extensão instalada",
  installed_how_title: "Como a extensão funciona:",
  installed_step_1: "Vá para a seção de música",
  installed_step_2: "Ao lado de cada faixa aparecerá um botão de download e informações sobre o bitrate.",
  installed_step_3: "Clique no botão para baixar a faixa.",
  installed_reload_notice: "Se você já tem o site {site} aberto, precisa recarregar a guia para que a extensão funcione.",
  installed_attention: "Atenção",
  installed_pc_version_only: "A extensão funciona apenas na versão completa do site {site}. Ao usar a versão móvel m.vk.ru, a extensão não funcionará.",
  installed_follow_community: "Siga {link}. Lá são publicadas informações importantes para os usuários da extensão!",
  installed_follow_community_link: "nossa comunidade no VK",
  installed_ffmpeg_notice_1: "Se você usa Firefox e as faixas não baixam, o problema provavelmente está no ffmpeg (conversão de faixas).",
  installed_ffmpeg_notice_2: "O VK entrega faixas no formato m3u8, e a extensão converte para o habitual mp3.",
  installed_ffmpeg_notice_3: "No Firefox, por padrão, a extensão usa o FFmpeg hospedado em nosso site {site}. Se o site estiver indisponível, a conversão não funciona e a extensão não poderá baixar a faixa.",
  installed_ffmpeg_notice_4: "Nas configurações da extensão, é possível mudar para o método hls.js. Ele não depende do nosso site, mas no Firefox funciona de forma instável — possíveis estalos ou distorções no som.",
  vms_concurrent_downloads_recommendation: "Não baixe mais de duas playlists de uma vez, caso contrário o navegador pode travar",
  vms_settings_need_reload_page: "Recarregue a página para que as alterações entrem em vigor"
};
export default lang;