const lang = {
  vms_download: "Descarcă",
  vms_loading: "Se încarcă...",
  vms_error: "Eroare",
  vms_download_cover: "Descarcă coperta",
  vms_download_playlist: "Descarcă playlist",
  vms_downloading: "Se descarcă...",
  vms_playlist_is_empty: "Playlist-ul este gol.",
  vms_playlist_not_found: "Playlist-ul nu a fost găsit",
  vms_audio_not_found: 'Не удалось получить данные о треке',
  vms_audio_url_not_found: "Link-ul piesei lipsește",
  vms_album_cover_not_found: "Acest album nu are copertă",
  vms_fs_music_done: "Descărcare muzică finalizată",
  vms_fs_music_playlist_done: "Descărcare playlist finalizată",
  vms_fs_method_selection: "Selectați metoda de descărcare",
  vms_fs_error_selecting_directory: "Eroare: nu s-a putut selecta folderul",
  vms_fs_option_zip_title: "Arhivă ZIP",
  vms_fs_option_zip_description: 'Скачивание одним файлом. Архивация происходит в процессе скачивания без нагрузки на систему.',
  vms_fs_option_folder_title: "Direct în folder",
  vms_fs_option_folder_description: 'Вам будет предложен выбор места для создания новой папки, в которую загрузятся файлы напрямую на диск.',
  vms_fs_option_unselected_title: "Întreabă mereu",
  vms_fs_download_method_title: "Metodă descărcare fișiere",
  vms_fs_select_zip: "Descarcă",
  vms_fs_select_folder: "Alege folder",
  vms_download_all_my_music: "Descarcă toată muzica mea",
  vms_download_all_music: "Descarcă toată muzica acestui utilizator",
  vms_sett_num_tracks_in_playlist: "Numerotează piesele în playlist",
  vms_sett_save_method_selection: "Memorează metoda selectată",
  vms_sett_save_method_selection_description: "Puteți schimba oricând în setări",
  vms_playlist_download_auth_required: 'Для скачивания плейлистов необходимо войти в аккаунт',
  vms_download_manager_active_tasks: "Descărcări active",
  vms_download_manager_finished_tasks: "Descărcări finalizate",
  vms_download_manager_save: "Salvează",
  vms_download_manager_remove: "Șterge",
  vms_download_manager_cancel: "Anulează",
  vms_playlist_track_download_completed: '{trackName} — завершено',
  vms_playlist_download_completed: `Descărcat {total}`,
  vms_tracks_plurals: ["piesă", "piese", "piese"],
  vms_sett_audio_convert_mode_title: "Metodă conversie",
  vms_sett_audio_convert_mode_ffmpeg_desc: "Posibil să nu funcționeze pe sisteme vechi.",
  vms_sett_audio_convert_mode_hlsjs_desc: "Pot apărea probleme în Firefox.",
  vms_sett_audio_convert_mode_desc: "VK oferă piese în m3u8, extensia le convertește în mp3.",
  vms_sett_audio_convert_mode_vknext: "Server VK Next",
  vms_sett_audio_convert_mode_vknext_desc: 'Использует FFmpeg на сервере. Идеально для больших плейлистов так как не нагружает ваш процессор. При высокой нагрузке на сервер скорость может снижаться.',
  vms_settings_title: "Setări VK Music Saver",
  vms_settings_review_in_firefox: "Evaluează în Firefox Add-ons",
  vms_settings_review_in_chrome: "Evaluează în Chrome Web Store",
  vms_settings_donate: "Susține dezvoltatorii",
  vms_share: "Distribuie",
  vms_clear_storage: "Resetează setările",
  vms_created_by: "Creat de echipa {name}",
  vms_link_copied: "Link copiat",
  vms_badges_deluxe_function_warning: "Funcție disponibilă pentru abonații Prime Deluxe.",
  vms_onboarding_settings_hint_title: "Setări VK Music Saver",
  vms_onboarding_settings_hint_description: "Aici puteți configura descărcarea după preferințe",
  vms_sett_single_track_template: "Format nume piesă individuală",
  vms_sett_playlist_track_template: "Format nume piesă în playlist",
  vms_sett_audio_write_id3_tags: "Adaugă etichete ID3",
  vms_sett_audio_write_id3_tags_desc: "Piesele vor avea metadate precum artist, titlu, dată și copertă",
  vms_sett_audio_write_genius_lyrics: "Inserează versuri Genius",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver nu este afiliat cu acest site și nu răspunde de corectitudinea versurilor",
  vms_sett_show_bitrate_near_duration: "Arată bitrate lângă durată",
  vms_alert_rating_title: "Vă place VK Music Saver?",
  vms_alert_rating_desc: "Vă rugăm să ne susțineți cu o evaluare în {storeName}",
  vms_alert_rating_yes: "Evaluează extensia",
  vms_alert_donate_title: "Susține dezvoltatorii",
  vms_alert_donate_desc: "VK Music Saver este gratuit, fără reclame. Dacă vă place, susțineți-ne cu o donație.",
  vms_alert_donate_yes: "Susține",
  vms_alert_base_no: "Nu, mulțumesc",
  vms_sett_download_playlist_in_reverse: "Descarcă playlist invers (de la ultima piesă)",
  vms_vmk_warning_title: "Extensia nu funcționează pe versiunea mobilă",
  vms_vmk_warning_go_vkcom: "Mergi la versiunea desktop",
  vms_vmk_warning_hide: "Nu mai arăta",
  vms_sett_add_leading_zeros: "Adaugă zero în fața numerelor",
  vms_sett_add_leading_zeros_desc: "Exemplu: 01, 02… în loc de 1, 2",
  installed_header_title: 'VK Music Saver установлен',
  installed_how_title: "Cum funcționează:",
  installed_step_1: 'Перейдите в раздел с музыкой по ссылке {vkRuAudio} ({vkComAudio}).',
  installed_step_2: 'Рядом с каждым треком отобразится кнопка скачивания, информация о битрейте и размере трека.',
  installed_step_3: "Apăsați butonul pentru a descărca.",
  installed_reload_notice: 'Если у вас уже открыт сайт {vkRu} ({vkCom}), нужно перезагрузить вкладку, чтобы расширение заработало.',
  installed_attention: "Atenție",
  installed_pc_version_only: 'Расширение работает только в полной версии сайта {vkRu} ({vkCom}). При использовании мобильной версии {mobileVkRu} ({mobileVkCom}), расширение не будет работать.',
  installed_follow_community: 'Подпишитесь на {vkRuVkNext}. Там оперативно выкладывается важная информация для пользователей расширения!',
  installed_follow_community_link: "comunitatea noastră VK",
  installed_convert_method_notice_1: 'Если треки не скачиваются или файл весит 0 байт, скорее всего, возникла ошибка на этапе конвертации.',
  installed_convert_method_notice_2: 'ВКонтакте отдает музыку в формате m3u8, а расширение конвертирует в привычный mp3.',
  installed_convert_method_notice_3: 'Попробуйте переключиться на метод FFmpeg в настройках. На разных устройствах и браузерах лучше работают разные методы.',
  installed_convert_method_notice_4: 'Настройки расширения находятся в меню профиля в правом верхнем углу (там, где ваша аватарка).',
  vms_concurrent_downloads_recommendation: "Nu descărcați mai mult de două playlist-uri simultan, browserul se poate bloca",
  vms_settings_need_reload_page: "Reîncărcați pagina pentru aplicarea setărilor"
};
export default lang;