const lang = {
  vms_download: "Descarcă",
  vms_loading: "Se încarcă...",
  vms_error: "Eroare",
  vms_download_cover: "Descarcă coperta",
  vms_download_playlist: "Descarcă playlist",
  vms_downloading: "Se descarcă...",
  vms_playlist_is_empty: "Playlist-ul este gol.",
  vms_playlist_not_found: "Playlist-ul nu a fost găsit",
  vms_audio_not_found: "VK nu a returnat informații despre piesă",
  vms_audio_url_not_found: "Link-ul piesei lipsește",
  vms_album_cover_not_found: "Acest album nu are copertă",
  vms_archivation: "arhivare...",
  vms_fs_music_done: "Descărcare muzică finalizată",
  vms_fs_music_playlist_done: "Descărcare playlist finalizată",
  vms_fs_method_selection: "Selectați metoda de descărcare",
  vms_fs_error_selecting_directory: "Eroare: nu s-a putut selecta folderul",
  vms_fs_option_zip_title: "Arhivă ZIP",
  vms_fs_option_zip_description: "Toate fișierele vor fi descărcate în RAM și apoi arhivate. Vi se va cere să salvați arhiva.",
  vms_fs_option_folder_title: "Direct în folder",
  vms_fs_option_folder_description: "Vi se va cere să alegeți un folder nou unde fișierele se vor descărca direct fără a folosi RAM.",
  vms_fs_option_unselected_title: "Întreabă mereu",
  vms_fs_download_method_title: "Metodă descărcare fișiere",
  vms_fs_select_zip: "Descarcă",
  vms_fs_select_folder: "Alege folder",
  vms_fs_select_recommended: "Metodă recomandată",
  vms_download_all_my_music: "Descarcă toată muzica mea",
  vms_download_all_music: "Descarcă toată muzica acestui utilizator",
  vms_sett_num_tracks_in_playlist: "Numerotează piesele în playlist",
  vms_sett_save_method_selection: "Memorează metoda selectată",
  vms_sett_save_method_selection_description: "Puteți schimba oricând în setări",
  vms_playlist_download_auth_required: "Trebuie să fiți autentificat pentru a descărca playlist-uri",
  vms_download_manager_active_tasks: "Descărcări active",
  vms_download_manager_finished_tasks: "Descărcări finalizate",
  vms_download_manager_save: "Salvează",
  vms_download_manager_remove: "Șterge",
  vms_download_manager_cancel: "Anulează",
  vms_playlist_track_download_completed: "{trackName} - finalizat",
  vms_playlist_download_completed: `Descărcat {total}`,
  vms_tracks_plurals: ["piesă", "piese", "piese"],
  vms_sett_audio_convert_mode_title: "Metodă conversie",
  vms_sett_audio_convert_mode_ffmpeg_desc: "Posibil să nu funcționeze pe sisteme vechi.",
  vms_sett_audio_convert_mode_hlsjs_desc: "Pot apărea probleme în Firefox.",
  vms_sett_audio_convert_mode_desc: "VK oferă piese în m3u8, extensia le convertește în mp3.",
  vms_sett_audio_convert_mode_vknext: "Server VK Next",
  vms_sett_audio_convert_mode_vknext_desc: "Folosește FFmpeg. Mai bun pentru playlist-uri mari deoarece nu ocupă RAM. Poate fi lent dacă e aglomerat.",
  vms_settings_title: "Setări VK Music Saver",
  vms_settings_review_in_firefox: "Evaluează în Firefox Add-ons",
  vms_settings_review_in_chrome: "Evaluează în Chrome Web Store",
  vms_settings_donate: "Susține dezvoltatorii",
  vms_share: "Distribuie",
  vms_clear_storage: "Resetează setările",
  vms_created_by: "Creat de echipa {name}",
  vms_link_copied: "Link copiat",
  vms_badges_deluxe_function_warning: "Funcție disponibilă pentru abonații Prime Deluxe.",
  vms_onboarding_settings_hint_title: "Setări VK Music Saver",
  vms_onboarding_settings_hint_description: "Aici puteți configura descărcarea după preferințe",
  vms_sett_single_track_template: "Format nume piesă individuală",
  vms_sett_playlist_track_template: "Format nume piesă în playlist",
  vms_sett_audio_write_id3_tags: "Adaugă etichete ID3",
  vms_sett_audio_write_id3_tags_desc: "Piesele vor avea metadate precum artist, titlu, dată și copertă",
  vms_sett_audio_write_genius_lyrics: "Inserează versuri Genius",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver nu este afiliat cu acest site și nu răspunde de corectitudinea versurilor",
  vms_sett_show_bitrate_near_duration: "Arată bitrate lângă durată",
  vms_alert_rating_title: "Vă place VK Music Saver?",
  vms_alert_rating_desc: "Vă rugăm să ne susțineți cu o evaluare în {storeName}",
  vms_alert_rating_yes: "Evaluează extensia",
  vms_alert_donate_title: "Susține dezvoltatorii",
  vms_alert_donate_desc: "VK Music Saver este gratuit, fără reclame. Dacă vă place, susțineți-ne cu o donație.",
  vms_alert_donate_yes: "Susține",
  vms_alert_base_no: "Nu, mulțumesc",
  vms_sett_download_playlist_in_reverse: "Descarcă playlist invers (de la ultima piesă)",
  vms_vmk_warning_title: "Extensia nu funcționează pe versiunea mobilă",
  vms_vmk_warning_go_vkcom: "Mergi la versiunea desktop",
  vms_vmk_warning_hide: "Nu mai arăta",
  vms_sett_add_leading_zeros: "Adaugă zero în fața numerelor",
  vms_sett_add_leading_zeros_desc: "Exemplu: 01, 02… în loc de 1, 2",
  installed_header_title: "Extensie instalată",
  installed_how_title: "Cum funcționează:",
  installed_step_1: "Mergeți la secțiunea muzică",
  installed_step_2: "Lângă fiecare piesă apare butonul de descărcare și bitrate-ul.",
  installed_step_3: "Apăsați butonul pentru a descărca.",
  installed_reload_notice: "Dacă {site} este deja deschis, reîncărcați pagina.",
  installed_attention: "Atenție",
  installed_pc_version_only: "Funcționează doar pe versiunea completă {site}, nu pe m.vk.ru.",
  installed_follow_community: "Abonează-te la {link} pentru noutăți importante!",
  installed_follow_community_link: "comunitatea noastră VK",
  installed_ffmpeg_notice_1: "Dacă folosiți Firefox și descărcarea nu merge, problema e la ffmpeg.",
  installed_ffmpeg_notice_2: "VK dă m3u8, extensia convertește în mp3.",
  installed_ffmpeg_notice_3: "În Firefox se folosește FFmpeg de pe site-ul nostru {site}. Dacă site-ul e jos, conversia nu merge.",
  installed_ffmpeg_notice_4: "Puteți schimba pe hls.js în setări. E instabil în Firefox (posibile distorsiuni).",
  vms_concurrent_downloads_recommendation: "Nu descărcați mai mult de două playlist-uri simultan, browserul se poate bloca",
  vms_settings_need_reload_page: "Reîncărcați pagina pentru aplicarea setărilor"
};
export default lang;