const lang = {
  vms_download: "Descargar",
  vms_loading: "Cargando...",
  vms_error: "Error",
  vms_download_cover: "Descargar portada",
  vms_download_playlist: "Descargar lista de reproducción",
  vms_downloading: "Descargando...",
  vms_playlist_is_empty: "La lista está vacía.",
  vms_playlist_not_found: "Lista no encontrada",
  vms_audio_not_found: "VK no devolvió información de la pista",
  vms_audio_url_not_found: "Falta el enlace de la pista",
  vms_album_cover_not_found: "Este álbum no tiene portada",
  vms_archivation: "archivando...",
  vms_fs_music_done: "Descarga de música completada",
  vms_fs_music_playlist_done: "Descarga de lista completada",
  vms_fs_method_selection: "Seleccionar método de descarga",
  vms_fs_error_selecting_directory: "Error: no se pudo seleccionar la carpeta",
  vms_fs_option_zip_title: "Archivo ZIP",
  vms_fs_option_zip_description: "Todos los archivos se descargarán a la RAM y luego se comprimirán en un archivo. Se le pedirá que lo guarde.",
  vms_fs_option_folder_title: "Directamente a carpeta",
  vms_fs_option_folder_description: "Se le pedirá elegir una ubicación para una nueva carpeta donde los archivos se descargarán sin usar la RAM.",
  vms_fs_option_unselected_title: "Preguntar siempre",
  vms_fs_download_method_title: "Método de descarga",
  vms_fs_select_zip: "Descargar",
  vms_fs_select_folder: "Elegir carpeta",
  vms_fs_select_recommended: "Método recomendado",
  vms_download_all_my_music: "Descargar toda mi música",
  vms_download_all_music: "Descargar toda la música de este usuario",
  vms_sett_num_tracks_in_playlist: "Numerar pistas en la lista",
  vms_sett_save_method_selection: "Recordar método de descarga",
  vms_sett_save_method_selection_description: "Siempre puedes cambiarlo en la configuración",
  vms_playlist_download_auth_required: "Debes iniciar sesión para descargar listas",
  vms_download_manager_active_tasks: "Descargas activas",
  vms_download_manager_finished_tasks: "Descargas finalizadas",
  vms_download_manager_save: "Guardar",
  vms_download_manager_remove: "Eliminar",
  vms_download_manager_cancel: "Cancelar",
  vms_playlist_track_download_completed: "{trackName} - completado",
  vms_playlist_download_completed: `Descargado {total}`,
  vms_tracks_plurals: ["pista", "pistas", "pistas"],
  vms_sett_audio_convert_mode_title: "Método de conversión",
  vms_sett_audio_convert_mode_ffmpeg_desc: "Puede no funcionar en sistemas antiguos.",
  vms_sett_audio_convert_mode_hlsjs_desc: "Puede haber problemas en Firefox.",
  vms_sett_audio_convert_mode_desc: "VK entrega pistas en formato m3u8, y la extensión las convierte a mp3.",
  vms_sett_audio_convert_mode_vknext: "Servidor VK Next",
  vms_sett_audio_convert_mode_vknext_desc: "Usa FFmpeg para conversión. Mejor para listas grandes ya que no ocupa RAM. Puede ser lento si hay muchos usuarios.",
  vms_settings_title: "Configuración de VK Music Saver",
  vms_settings_review_in_firefox: "Calificar en Firefox Add-ons",
  vms_settings_review_in_chrome: "Calificar en Chrome Web Store",
  vms_settings_donate: "Apoyar a los desarrolladores",
  vms_share: "Compartir",
  vms_clear_storage: "Restablecer configuración",
  vms_created_by: "Creado por el equipo {name}",
  vms_link_copied: "Enlace copiado",
  vms_badges_deluxe_function_warning: "Función disponible para suscriptores Prime Deluxe.",
  vms_onboarding_settings_hint_title: "Configuración VK Music Saver",
  vms_onboarding_settings_hint_description: "Aquí puedes configurar la descarga a tu gusto",
  vms_sett_single_track_template: "Formato nombre pista individual",
  vms_sett_playlist_track_template: "Formato nombre pista en lista",
  vms_sett_audio_write_id3_tags: "Añadir etiquetas ID3",
  vms_sett_audio_write_id3_tags_desc: "Las pistas tendrán metadatos como artista, título, fecha y portada",
  vms_sett_audio_write_genius_lyrics: "Insertar letras de Genius en metadatos",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver no está afiliado con ese sitio y no es responsable de la exactitud de las letras",
  vms_sett_show_bitrate_near_duration: "Mostrar bitrate junto a la duración",
  vms_alert_rating_title: "¿Te gusta VK Music Saver?",
  vms_alert_rating_desc: "Por favor apoya la extensión calificándola en {storeName}",
  vms_alert_rating_yes: "Calificar extensión",
  vms_alert_donate_title: "Apoya a los desarrolladores",
  vms_alert_donate_desc: "VK Music Saver es gratuito, sin anuncios ni rastreo. Si te gusta, apóyanos con una donación.",
  vms_alert_donate_yes: "Apoyar",
  vms_alert_base_no: "No, gracias",
  vms_sett_download_playlist_in_reverse: "Descargar listas en orden inverso",
  vms_vmk_warning_title: "La extensión no funciona en la versión móvil",
  vms_vmk_warning_go_vkcom: "Ir a la versión de escritorio",
  vms_vmk_warning_hide: "No mostrar de nuevo",
  vms_sett_add_leading_zeros: "Añadir ceros a los números de pista",
  vms_sett_add_leading_zeros_desc: "Ejemplo: 01, 02… en lugar de 1, 2",
  installed_header_title: "Extensión instalada",
  installed_how_title: "Cómo funciona:",
  installed_step_1: "Ve a la sección de música",
  installed_step_2: "Aparecerá un botón de descarga e info de bitrate junto a cada pista.",
  installed_step_3: "Haz clic para descargar.",
  installed_reload_notice: "Si ya tienes {site} abierto, recarga la pestaña para que funcione.",
  installed_attention: "Atención",
  installed_pc_version_only: "Funciona solo en la versión completa de {site}, no en m.vk.ru.",
  installed_follow_community: "Suscríbete a {link} para novedades importantes.",
  installed_follow_community_link: "nuestra comunidad VK",
  installed_ffmpeg_notice_1: "Si usas Firefox y falla la descarga, suele ser problema de ffmpeg.",
  installed_ffmpeg_notice_2: "VK usa m3u8 y la extensión lo convierte a mp3.",
  installed_ffmpeg_notice_3: "En Firefox se usa FFmpeg alojado en nuestro sitio {site}. Si el sitio cae, la conversión falla.",
  installed_ffmpeg_notice_4: "Puedes cambiar a hls.js en ajustes. No depende de nuestro sitio pero es inestable en Firefox.",
  vms_concurrent_downloads_recommendation: "No descargues más de dos listas a la vez o el navegador podría congelarse",
  vms_settings_need_reload_page: "Recarga la página para aplicar cambios"
};
export default lang;