const lang = {
  vms_download: "Descargar",
  vms_loading: "Cargando...",
  vms_error: "Error",
  vms_download_cover: "Descargar portada",
  vms_download_playlist: "Descargar lista de reproducción",
  vms_downloading: "Descargando...",
  vms_playlist_is_empty: "La lista está vacía.",
  vms_playlist_not_found: "Lista no encontrada",
  vms_audio_not_found: "No se pudieron obtener los datos de la pista",
  vms_audio_url_not_found: "Falta el enlace de la pista",
  vms_album_cover_not_found: "Este álbum no tiene portada",
  vms_fs_music_done: "Descarga de música completada",
  vms_fs_music_playlist_done: "Descarga de lista completada",
  vms_fs_method_selection: "Seleccionar método de descarga",
  vms_fs_error_selecting_directory: "Error: no se pudo seleccionar la carpeta",
  vms_fs_option_zip_title: "Archivo ZIP",
  vms_fs_option_zip_description: "Descargar como un solo archivo. El archivado se realiza durante la descarga sin sobrecargar el sistema.",
  vms_fs_option_folder_title: "Directamente a carpeta",
  vms_fs_option_folder_description: "Se le pedirá que elija una ubicación para crear una nueva carpeta en la que los archivos se descargarán directamente al disco.",
  vms_fs_option_unselected_title: "Preguntar siempre",
  vms_fs_download_method_title: "Método de descarga",
  vms_fs_select_zip: "Descargar",
  vms_fs_select_folder: "Elegir carpeta",
  vms_download_all_my_music: "Descargar toda mi música",
  vms_download_all_music: "Descargar toda la música de este usuario",
  vms_sett_num_tracks_in_playlist: "Numerar pistas en la lista",
  vms_sett_save_method_selection: "Recordar método de descarga",
  vms_sett_save_method_selection_description: "Siempre puedes cambiarlo en la configuración",
  vms_playlist_download_auth_required: "Para descargar listas de reproducción, es necesario iniciar sesión",
  vms_download_manager_active_tasks: "Descargas activas",
  vms_download_manager_finished_tasks: "Descargas finalizadas",
  vms_download_manager_save: "Guardar",
  vms_download_manager_remove: "Eliminar",
  vms_download_manager_cancel: "Cancelar",
  vms_playlist_track_download_completed: "{trackName} — completado",
  vms_playlist_download_completed: `Descargado {total}`,
  vms_tracks_plurals: ["pista", "pistas", "pistas"],
  vms_sett_audio_convert_mode_title: "Método de conversión",
  vms_sett_audio_convert_mode_ffmpeg_desc: "Puede no funcionar en sistemas antiguos.",
  vms_sett_audio_convert_mode_desc: "VK entrega pistas en formato m3u8, y la extensión las convierte a mp3.",
  vms_sett_audio_convert_mode_vknext: "Servidor VK Next",
  vms_sett_audio_convert_mode_vknext_desc: "Utiliza FFmpeg en el servidor. Ideal para listas de reproducción grandes, ya que no carga su procesador. La velocidad puede disminuir con una alta carga del servidor.",
  vms_settings_title: "Configuración de VK Music Saver",
  vms_settings_review_in_firefox: "Calificar en Firefox Add-ons",
  vms_settings_review_in_chrome: "Calificar en Chrome Web Store",
  vms_settings_donate: "Apoyar a los desarrolladores",
  vms_share: "Compartir",
  vms_clear_storage: "Restablecer configuración",
  vms_clear_track_details_storage: 'Очистить кэш треков',
  vms_clear_track_details_storage_description: 'Размер и битрейт',
  vms_created_by: "Creado por el equipo {name}",
  vms_link_copied: "Enlace copiado",
  vms_badges_deluxe_function_warning: "Función disponible para suscriptores Prime Deluxe.",
  vms_onboarding_settings_hint_title: "Configuración VK Music Saver",
  vms_onboarding_settings_hint_description: "Aquí puedes configurar la descarga a tu gusto",
  vms_sett_single_track_template: "Formato nombre pista individual",
  vms_sett_playlist_track_template: "Formato nombre pista en lista",
  vms_sett_audio_write_id3_tags: "Añadir etiquetas ID3",
  vms_sett_audio_write_id3_tags_desc: "Las pistas tendrán metadatos como artista, título, fecha y portada",
  vms_sett_audio_write_genius_lyrics: "Insertar letras de Genius en metadatos",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver no está afiliado con ese sitio y no es responsable de la exactitud de las letras",
  vms_sett_show_bitrate_near_duration: "Mostrar bitrate junto a la duración",
  vms_alert_rating_title: "¿Te gusta VK Music Saver?",
  vms_alert_rating_desc: "Por favor apoya la extensión calificándola en {storeName}",
  vms_alert_rating_yes: "Calificar extensión",
  vms_alert_donate_title: "Apoya a los desarrolladores",
  vms_alert_donate_desc: "VK Music Saver es gratuito, sin anuncios ni rastreo. Si te gusta, apóyanos con una donación.",
  vms_alert_donate_yes: "Apoyar",
  vms_alert_base_no: "No, gracias",
  vms_sett_download_playlist_in_reverse: "Descargar listas en orden inverso",
  vms_vmk_warning_title: "La extensión no funciona en la versión móvil",
  vms_vmk_warning_go_vkcom: "Ir a la versión de escritorio",
  vms_vmk_warning_hide: "No mostrar de nuevo",
  vms_sett_add_leading_zeros: "Añadir ceros a los números de pista",
  vms_sett_add_leading_zeros_desc: "Ejemplo: 01, 02… en lugar de 1, 2",
  vms_concurrent_downloads_recommendation: "No descargues más de dos listas a la vez o el navegador podría congelarse",
  vms_settings_need_reload_page: "Recarga la página para aplicar cambios"
};
export default lang;