const lang = {
  vms_download: "İndir",
  vms_loading: "Yükleniyor...",
  vms_error: "Hata",
  vms_download_cover: "Kapağı indir",
  vms_download_playlist: "Çalma listesini indir",
  vms_downloading: "İndiriliyor...",
  vms_playlist_is_empty: "Çalma listesi boş.",
  vms_playlist_not_found: "Çalma listesi bulunamadı",
  vms_audio_not_found: "Parça verileri alınamadı",
  vms_audio_url_not_found: "Parça bağlantısı yok",
  vms_album_cover_not_found: "Bu albümün kapağı yok",
  vms_fs_music_done: "Müzik indirme tamamlandı",
  vms_fs_music_playlist_done: "Çalma listesi indirme tamamlandı",
  vms_fs_method_selection: "İndirme yöntemini seçin",
  vms_fs_error_selecting_directory: "Hata: kayıt klasörü seçilemedi",
  vms_fs_option_zip_title: "ZIP arşivi",
  vms_fs_option_zip_description: "Tek dosya olarak indirme. Arşivleme, indirme işlemi sırasında sistemi yormadan gerçekleşir.",
  vms_fs_option_folder_title: "Doğrudan klasöre",
  vms_fs_option_folder_description: "Dosyaların doğrudan diske indirileceği yeni bir klasör oluşturmak için bir konum seçmeniz isteniyor.",
  vms_fs_option_unselected_title: "Her zaman sor",
  vms_fs_download_method_title: "Dosya indirme yöntemi",
  vms_fs_select_zip: "İndir",
  vms_fs_select_folder: "Klasör seç",
  vms_download_all_my_music: "Tüm müziklerimi indir",
  vms_download_all_music: "Bu kullanıcının tüm müziklerini indir",
  vms_sett_num_tracks_in_playlist: "Çalma listesinde parçaları numaralandır",
  vms_sett_save_method_selection: "Seçilen yöntemi hatırla",
  vms_sett_save_method_selection_description: "Ayarlardan her zaman değiştirebilirsiniz",
  vms_playlist_download_auth_required: "Çalma listelerini indirmek için giriş yapmanız gerekiyor",
  vms_download_manager_active_tasks: "Aktif indirmeler",
  vms_download_manager_finished_tasks: "Tamamlanan indirmeler",
  vms_download_manager_save: "Kaydet",
  vms_download_manager_remove: "Kaldır",
  vms_download_manager_cancel: "İptal",
  vms_playlist_track_download_completed: "{trackName} — tamamlandı",
  vms_playlist_download_completed: `İndirilen {total}`,
  vms_tracks_plurals: ["parça", "parça", "parça"],
  vms_sett_audio_convert_mode_title: "Dönüştürme yöntemi",
  vms_sett_audio_convert_mode_ffmpeg_desc: "Eski sistemlerde çalışmayabilir.",
  vms_sett_audio_convert_mode_hlsjs_desc: "Firefox'ta sorunlar olabilir.",
  vms_sett_audio_convert_mode_desc: "VK parçaları m3u8 formatında verir, uzantı mp3'e dönüştürür.",
  vms_sett_audio_convert_mode_vknext: "VK Next Sunucusu",
  vms_sett_audio_convert_mode_vknext_desc: "Sunucuda FFmpeg kullanır. İşlemcinizi yormadığı için büyük çalma listeleri için idealdir. Sunucu yükü yüksek olduğunda hız düşebilir.",
  vms_settings_title: "VK Music Saver Ayarları",
  vms_settings_review_in_firefox: "Firefox Add-ons'ta puanla",
  vms_settings_review_in_chrome: "Chrome Web Store'da puanla",
  vms_settings_donate: "Geliştiricileri destekle",
  vms_share: "Paylaş",
  vms_clear_storage: "Ayarları sıfırla",
  vms_created_by: "{name} ekibi tarafından oluşturuldu",
  vms_link_copied: "Bağlantı kopyalandı",
  vms_badges_deluxe_function_warning: "Özellik Prime Deluxe aboneleri içindir.",
  vms_onboarding_settings_hint_title: "VK Music Saver Ayarları",
  vms_onboarding_settings_hint_description: "İndirme işlemlerini buradan özelleştirebilirsiniz",
  vms_sett_single_track_template: "Tekli parça adı formatı",
  vms_sett_playlist_track_template: "Çalma listesi parça adı formatı",
  vms_sett_audio_write_id3_tags: "Müziğe ID3 etiketleri ekle",
  vms_sett_audio_write_id3_tags_desc: "Parçalar sanatçı, başlık, tarih ve kapak gibi meta verilerle indirilir",
  vms_sett_audio_write_genius_lyrics: "Genius şarkı sözlerini ekle",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver bu siteyle bağlantılı değildir ve söz doğruluğundan sorumlu değildir",
  vms_sett_show_bitrate_near_duration: "Sürenin yanında bit hızını göster",
  vms_alert_rating_title: "VK Music Saver'ı sevdiniz mi?",
  vms_alert_rating_desc: "Lütfen {storeName}'de puanlayarak destek olun",
  vms_alert_rating_yes: "Uzantıyı puanla",
  vms_alert_donate_title: "Geliştiricileri destekleyin",
  vms_alert_donate_desc: "VK Music Saver gönüllülükle geliştirilir — ücretsiz, reklamsız, veri toplamaz. Beğendiyseniz bağışla destekleyin.",
  vms_alert_donate_yes: "Destekle",
  vms_alert_base_no: "Hayır, teşekkürler",
  vms_sett_download_playlist_in_reverse: "Çalma listelerini tersten indir (sondan başa)",
  vms_vmk_warning_title: "Uzantı mobil sürümde çalışmaz",
  vms_vmk_warning_go_vkcom: "Masaüstü sürümüne git",
  vms_vmk_warning_hide: "Bir daha gösterme",
  vms_sett_add_leading_zeros: "Parça numaralarına başında sıfır ekle",
  vms_sett_add_leading_zeros_desc: "Örnek: 1, 2 yerine 01, 02…",
  installed_header_title: "VK Music Saver yüklendi",
  installed_how_title: "Nasıl çalışır:",
  installed_step_1: "{vkRuAudio} ({vkComAudio}) bağlantısı üzerinden müzik bölümüne gidin.",
  installed_step_2: "Her parçanın yanında bir indirme düğmesi, bit hızı bilgisi ve parça boyutu görüntülenecektir.",
  installed_step_3: "İndirmek için butona basın.",
  installed_reload_notice: "{vkRu} ({vkCom}) sitesi zaten açıksa, eklentinin çalışması için sekmeyi yeniden yüklemeniz gerekir.",
  installed_attention: "Dikkat",
  installed_pc_version_only: "Eklenti yalnızca {vkRu} ({vkCom}) sitesinin masaüstü sürümünde çalışır. {mobileVkRu} ({mobileVkCom}) mobil sürümü kullanılırken eklenti çalışmayacaktır.",
  installed_follow_community: "{vkRuVkNext} adresine abone olun. Eklenti kullanıcıları için önemli bilgiler anında orada paylaşılır!",
  installed_follow_community_link: "VK topluluğumuz",
  installed_convert_method_notice_1: "Parçalar indirilmiyorsa veya dosya boyutu 0 bayt ise, muhtemelen dönüştürme aşamasında bir hata oluşmuştur.",
  installed_convert_method_notice_2: "VKontakte müziği m3u8 formatında sunar ve eklenti bunu alışıldık mp3 formatına dönüştürür.",
  installed_convert_method_notice_3: "Ayarlardan FFmpeg yöntemine geçmeyi deneyin. Farklı cihaz ve tarayıcılarda farklı yöntemler daha iyi çalışır.",
  installed_convert_method_notice_4: "Eklenti ayarları sağ üst köşedeki profil menüsünde (avatarınızın olduğu yer) bulunur.",
  vms_concurrent_downloads_recommendation: "Aynı anda ikiden fazla liste indirmeyin, tarayıcı donabilir",
  vms_settings_need_reload_page: "Değişiklikler için sayfayı yenileyin"
};
export default lang;