const lang = {
  vms_download: "İndir",
  vms_loading: "Yükleniyor...",
  vms_error: "Hata",
  vms_download_cover: "Kapağı indir",
  vms_download_playlist: "Çalma listesini indir",
  vms_downloading: "İndiriliyor...",
  vms_playlist_is_empty: "Çalma listesi boş.",
  vms_playlist_not_found: "Çalma listesi bulunamadı",
  vms_audio_not_found: 'Не удалось получить данные о треке',
  vms_audio_url_not_found: "Parça bağlantısı yok",
  vms_album_cover_not_found: "Bu albümün kapağı yok",
  vms_fs_music_done: "Müzik indirme tamamlandı",
  vms_fs_music_playlist_done: "Çalma listesi indirme tamamlandı",
  vms_fs_method_selection: "İndirme yöntemini seçin",
  vms_fs_error_selecting_directory: "Hata: kayıt klasörü seçilemedi",
  vms_fs_option_zip_title: "ZIP arşivi",
  vms_fs_option_zip_description: 'Скачивание одним файлом. Архивация происходит в процессе скачивания без нагрузки на систему.',
  vms_fs_option_folder_title: "Doğrudan klasöre",
  vms_fs_option_folder_description: 'Вам будет предложен выбор места для создания новой папки, в которую загрузятся файлы напрямую на диск.',
  vms_fs_option_unselected_title: "Her zaman sor",
  vms_fs_download_method_title: "Dosya indirme yöntemi",
  vms_fs_select_zip: "İndir",
  vms_fs_select_folder: "Klasör seç",
  vms_download_all_my_music: "Tüm müziklerimi indir",
  vms_download_all_music: "Bu kullanıcının tüm müziklerini indir",
  vms_sett_num_tracks_in_playlist: "Çalma listesinde parçaları numaralandır",
  vms_sett_save_method_selection: "Seçilen yöntemi hatırla",
  vms_sett_save_method_selection_description: "Ayarlardan her zaman değiştirebilirsiniz",
  vms_playlist_download_auth_required: 'Для скачивания плейлистов необходимо войти в аккаунт',
  vms_download_manager_active_tasks: "Aktif indirmeler",
  vms_download_manager_finished_tasks: "Tamamlanan indirmeler",
  vms_download_manager_save: "Kaydet",
  vms_download_manager_remove: "Kaldır",
  vms_download_manager_cancel: "İptal",
  vms_playlist_track_download_completed: '{trackName} — завершено',
  vms_playlist_download_completed: `İndirilen {total}`,
  vms_tracks_plurals: ["parça", "parça", "parça"],
  vms_sett_audio_convert_mode_title: "Dönüştürme yöntemi",
  vms_sett_audio_convert_mode_ffmpeg_desc: "Eski sistemlerde çalışmayabilir.",
  vms_sett_audio_convert_mode_hlsjs_desc: "Firefox'ta sorunlar olabilir.",
  vms_sett_audio_convert_mode_desc: "VK parçaları m3u8 formatında verir, uzantı mp3'e dönüştürür.",
  vms_sett_audio_convert_mode_vknext: "VK Next Sunucusu",
  vms_sett_audio_convert_mode_vknext_desc: 'Использует FFmpeg на сервере. Идеально для больших плейлистов так как не нагружает ваш процессор. При высокой нагрузке на сервер скорость может снижаться.',
  vms_settings_title: "VK Music Saver Ayarları",
  vms_settings_review_in_firefox: "Firefox Add-ons'ta puanla",
  vms_settings_review_in_chrome: "Chrome Web Store'da puanla",
  vms_settings_donate: "Geliştiricileri destekle",
  vms_share: "Paylaş",
  vms_clear_storage: "Ayarları sıfırla",
  vms_created_by: "{name} ekibi tarafından oluşturuldu",
  vms_link_copied: "Bağlantı kopyalandı",
  vms_badges_deluxe_function_warning: "Özellik Prime Deluxe aboneleri içindir.",
  vms_onboarding_settings_hint_title: "VK Music Saver Ayarları",
  vms_onboarding_settings_hint_description: "İndirme işlemlerini buradan özelleştirebilirsiniz",
  vms_sett_single_track_template: "Tekli parça adı formatı",
  vms_sett_playlist_track_template: "Çalma listesi parça adı formatı",
  vms_sett_audio_write_id3_tags: "Müziğe ID3 etiketleri ekle",
  vms_sett_audio_write_id3_tags_desc: "Parçalar sanatçı, başlık, tarih ve kapak gibi meta verilerle indirilir",
  vms_sett_audio_write_genius_lyrics: "Genius şarkı sözlerini ekle",
  vms_sett_audio_write_genius_lyrics_desc: "VK Music Saver bu siteyle bağlantılı değildir ve söz doğruluğundan sorumlu değildir",
  vms_sett_show_bitrate_near_duration: "Sürenin yanında bit hızını göster",
  vms_alert_rating_title: "VK Music Saver'ı sevdiniz mi?",
  vms_alert_rating_desc: "Lütfen {storeName}'de puanlayarak destek olun",
  vms_alert_rating_yes: "Uzantıyı puanla",
  vms_alert_donate_title: "Geliştiricileri destekleyin",
  vms_alert_donate_desc: "VK Music Saver gönüllülükle geliştirilir — ücretsiz, reklamsız, veri toplamaz. Beğendiyseniz bağışla destekleyin.",
  vms_alert_donate_yes: "Destekle",
  vms_alert_base_no: "Hayır, teşekkürler",
  vms_sett_download_playlist_in_reverse: "Çalma listelerini tersten indir (sondan başa)",
  vms_vmk_warning_title: "Uzantı mobil sürümde çalışmaz",
  vms_vmk_warning_go_vkcom: "Masaüstü sürümüne git",
  vms_vmk_warning_hide: "Bir daha gösterme",
  vms_sett_add_leading_zeros: "Parça numaralarına başında sıfır ekle",
  vms_sett_add_leading_zeros_desc: "Örnek: 1, 2 yerine 01, 02…",
  installed_header_title: 'VK Music Saver установлен',
  installed_how_title: "Nasıl çalışır:",
  installed_step_1: 'Перейдите в раздел с музыкой по ссылке {vkRuAudio} ({vkComAudio}).',
  installed_step_2: 'Рядом с каждым треком отобразится кнопка скачивания, информация о битрейте и размере трека.',
  installed_step_3: "İndirmek için butona basın.",
  installed_reload_notice: 'Если у вас уже открыт сайт {vkRu} ({vkCom}), нужно перезагрузить вкладку, чтобы расширение заработало.',
  installed_attention: "Dikkat",
  installed_pc_version_only: 'Расширение работает только в полной версии сайта {vkRu} ({vkCom}). При использовании мобильной версии {mobileVkRu} ({mobileVkCom}), расширение не будет работать.',
  installed_follow_community: 'Подпишитесь на {vkRuVkNext}. Там оперативно выкладывается важная информация для пользователей расширения!',
  installed_follow_community_link: "VK topluluğumuz",
  installed_convert_method_notice_1: 'Если треки не скачиваются или файл весит 0 байт, скорее всего, возникла ошибка на этапе конвертации.',
  installed_convert_method_notice_2: 'ВКонтакте отдает музыку в формате m3u8, а расширение конвертирует в привычный mp3.',
  installed_convert_method_notice_3: 'Попробуйте переключиться на метод FFmpeg в настройках. На разных устройствах и браузерах лучше работают разные методы.',
  installed_convert_method_notice_4: 'Настройки расширения находятся в меню профиля в правом верхнем углу (там, где ваша аватарка).',
  vms_concurrent_downloads_recommendation: "Aynı anda ikiden fazla liste indirmeyin, tarayıcı donabilir",
  vms_settings_need_reload_page: "Değişiklikler için sayfayı yenileyin"
};
export default lang;