const lang = {
  vms_download: "Завантажити",
  vms_loading: "Завантажую...",
  vms_error: "Помилка",
  vms_download_cover: "Завантажити обкладинку",
  vms_download_playlist: "Завантажити плейлист",
  vms_downloading: "Завантажується...",
  vms_playlist_is_empty: "Плейлист порожній.",
  vms_playlist_not_found: "Плейлист не знайдено",
  vms_audio_not_found: "Трек не знайдено",
  vms_audio_url_not_found: "Відсутнє посилання на трек",
  vms_album_cover_not_found: "У цього альбому немає обкладинки",
  vms_archivation: 'архивация...',
  vms_fs_music_done: 'Скачивание музыки завершено: {folderName}',
  vms_fs_music_playlist_done: 'Скачивание плейлиста завершено: {folderName}',
  vms_fs_method_selection: 'Выберите способ скачивания файлов',
  vms_fs_error_selecting_directory: 'Ошибка: не удалось выбрать папку для сохранения',
  vms_fs_option_zip_title: 'zip-архив',
  vms_fs_option_zip_description: 'Все файлы будут загружены в оперативную память, а затем упакованы в архив, место сохранения которого будет предложено вам.',
  vms_fs_option_folder_title: 'Напрямую в папку',
  vms_fs_option_folder_description: 'Вам будет предложен выбор места для создания новой папки, в которую загрузятся файлы без предварительного сохранения в оперативной памяти.',
  vms_fs_select_zip: 'Скачать',
  vms_fs_select_folder: 'Выбрать папку',
  vms_fs_select_recommended: 'Рекомендуемый способ',
  vms_download_all_music: 'Скачать всю музыку'
};
export default lang;