const lang = {
	vms_download: 'Завантажити',
	vms_loading: 'Завантажую...',
	vms_error: 'Помилка',
	vms_download_cover: 'Завантажити обкладинку',
	vms_download_playlist: 'Завантажити плейлист',
	vms_downloading: 'Завантажується...',
	vms_playlist_is_empty: 'Плейлист порожній.',
	vms_playlist_not_found: 'Плейлист не знайдено',
	vms_audio_not_found: 'Не вдалося отримати дані про трек',
	vms_audio_url_not_found: 'Відсутнє посилання на трек',
	vms_album_cover_not_found: 'У цього альбому немає обкладинки',
	vms_fs_music_done: 'Завантаження музики завершено',
	vms_fs_music_playlist_done: 'Завантаження плейлиста завершено',
	vms_fs_method_selection: 'Виберіть спосіб завантаження файлів',
	vms_fs_error_selecting_directory: 'Помилка: не вдалося вибрати теку для збереження',
	vms_fs_option_zip_title: 'zip-архів',
	vms_fs_option_zip_description:
		'Завантаження одним файлом. Архівація відбувається в процесі завантаження без навантаження на систему.',
	vms_fs_option_folder_title: 'Безпосередньо в теку',
	vms_fs_option_folder_description:
		'Вам буде запропоновано вибрати місце для створення нової папки, в яку файли завантажуватимуться безпосередньо на диск.',
	vms_fs_option_unselected_title: 'Завжди запитувати',
	vms_fs_download_method_title: 'Спосіб завантаження файлів',
	vms_fs_select_zip: 'Завантажити',
	vms_fs_select_folder: 'Обрати теку',
	vms_download_all_my_music: 'Завантажити всі мої треки',
	vms_download_all_music: 'Завантажити всі треки цього користувача',
	vms_sett_num_tracks_in_playlist: 'Нумерувати треки у плейлисті',
	vms_sett_save_method_selection: "Запам'ятати обраний спосіб завантаження",
	vms_sett_save_method_selection_description: 'Ви завжди можете змінити спосіб у налаштуваннях додатку',
	vms_playlist_download_auth_required: 'Для завантаження плейлистів необхідно увійти в акаунт',
	vms_download_manager_active_tasks: 'Активні завантаження',
	vms_download_manager_finished_tasks: 'Завершені завантаження',
	vms_download_manager_save: 'Зберегти',
	vms_download_manager_remove: 'Видалити',
	vms_download_manager_cancel: 'Скасувати',
	vms_playlist_track_download_completed: '{trackName} — завершено',
	vms_playlist_download_completed: `Завантажено {total}`,
	vms_tracks_plurals: ['трек', 'треки', 'треків'],
	vms_sett_audio_convert_mode_title: 'Метод конвертації треків',
	vms_sett_audio_convert_mode_ffmpeg_desc: 'На старих системах може не працювати.',
	vms_sett_audio_convert_mode_desc: 'ВКонтакте віддає треки у форматі m3u8, а додаток конвертує у звичний mp3',
	vms_sett_audio_convert_mode_vknext: 'Сервер VK Next',
	vms_sett_audio_convert_mode_vknext_desc:
		'Використовує FFmpeg на сервері. Ідеально для великих плейлистів, оскільки не навантажує ваш процесор. При високому навантаженні на сервер швидкість може знижуватися.',
	vms_settings_title: 'Налаштування VK Music Saver',
	vms_settings_review_in_firefox: 'Оцінити в Firefox Add-ons',
	vms_settings_review_in_chrome: 'Оцінити в Chrome Web Store',
	vms_settings_donate: 'Підтримати розробників',
	vms_share: 'Поширити',
	vms_clear_storage: 'Скинути налаштування',
	vms_clear_track_details_storage: 'Очистить кэш треков',
	vms_clear_track_details_storage_description: 'Размер и битрейт',
	vms_created_by: 'Створено командою {name}',
	vms_link_copied: 'Посилання скопійовано',
	vms_badges_deluxe_function_warning: 'Функція доступна для власників підписки Прайм Де Люкс.',
	vms_onboarding_settings_hint_title: 'Налаштування VK Music Saver',
	vms_onboarding_settings_hint_description: 'У них можна налаштувати завантаження так, як зручно саме вам',
	vms_sett_single_track_template: 'Формат назви окремого треку',
	vms_sett_playlist_track_template: 'Формат назви треку у плейлисті',
	vms_sett_audio_write_id3_tags: 'Додавати ID3 теги до музики',
	vms_sett_audio_write_id3_tags_desc:
		"Треки та альбоми будуть завантажуватися з метаданими, такими як ім'я виконавця, назва, дата випуску та обкладинка",
	vms_sett_audio_write_genius_lyrics: 'Вставляти в метадані треків тексти з Genius',
	vms_sett_audio_write_genius_lyrics_desc:
		"VK Music Saver не пов'язаний із цим сайтом і не несе відповідальності за точність текстів пісень",
	vms_sett_show_bitrate_near_duration: 'Показувати бітрейт треку біля тривалості',
	vms_alert_rating_title: 'Вам подобається VK Music Saver?',
	vms_alert_rating_desc: 'Будь ласка, підтримайте додаток в рейтингу {storeName}',
	vms_alert_rating_yes: 'Оцінити додаток',
	vms_alert_donate_title: 'Підтримати розробників',
	vms_alert_donate_desc:
		'VK Music Saver створюється на ентузіазмі - безплатно, без реклами, без прихованих зборів даних і з відкритим вихідним кодом. Якщо додаток вам подобається, підтримайте нас донатом',
	vms_alert_donate_yes: 'Підтримати',
	vms_alert_base_no: 'Ні, дякую',
	vms_sett_download_playlist_in_reverse:
		'Завантажувати плейлисти у зворотному порядку - з останнього треку до першого',
	vms_vmk_warning_title: 'Додаток не працює в мобільній версії сайту',
	vms_vmk_warning_go_vkcom: "Перейти на комп'ютерну версію сайту",
	vms_vmk_warning_hide: 'Не показувати знову',
	vms_sett_add_leading_zeros: 'Форматувати номери треків із ведучими нулями',
	vms_sett_add_leading_zeros_desc: 'Наприклад: 01, 02, 03 ... замість 1, 2, 3',
	vms_concurrent_downloads_recommendation:
		'Завантажуйте не більше двох плейлистів одночасно, інакше браузер може зависнути',
	vms_settings_need_reload_page: 'Перезавантажте сторінку, щоб зміни набули чинності',
};
export default lang;
